### ISSUE TITLE
set page size from status bar select option

### ISSUE THREAD

**Issue by hemanth8888** [jqwidgets/jQWidgets#101]
i'm using jqxgrid with angular 7, when i render a status bar i am using html <select> tag to change page size i am getting the valu from  option selected but not able to set the page size with that value. its telling Cannot read property 'pagesize' of undefined. after using  (): voidi =>{ /// } this approch i am getting  Cannot read property 'toLowerCase' of undefined error. help me with this

**Comment by jqwidgets** [comment]
pagesize expects integer value. If other is set, an error would be thrown.
