### ISSUE TITLE
Feature Request: AutoHeight for Row details of jqxgrid with max height

### ISSUE THREAD

**Issue by jvutukur** [jqwidgets/jQWidgets#107]
RowDetails Template of jqxGrid does not have an option for auto row height.
With auto row height - there should be attribute for max height limitation when height goes more than this max height row should populate a vertical scroll bar

Example - 
 ```
 rowdetailstemplate: any = {
    rowdetails: '<div id="nestedGrid" style="margin: 10px;"></div>', 
    rowdetailsheight: auto,
    maxHeight: 300px;
   };
```

**Comment by jqwidgets** [comment]
Hello jvutukur,

Thank you for contacting us.
I will discuss this with my colleagues.
As a workaround I would like to suggest you the option to use **[jqxDataTable](https://www.jqwidgets.com/jquery-widgets-documentation/documentation/jqxdatatable/jquery-datatable-api.htm?search=jqxdatatable)**.
Please, take a look at this [example](http://jsfiddle.net/txhi/gsoa7wm8/).

Best Regards,
Hristo Hristov

jQWidgets team
https://www.jqwidgets.com

**Comment by jqwidgets** [comment]
Done in 8.1.3

**Comment by jvutukur** [comment]
What is the release date of 8.1.3 ?

**Comment by bmarkov** [comment]
Follow us on facebook or twitter for notifications about new versions. The features will allow setting custom height for a row detail.
