### ISSUE TITLE
Feature Request: Auto height for jqxwindow

### ISSUE THREAD

**Issue by jvutukur** [jqwidgets/jQWidgets#108]
https://stackblitz.com/edit/github-gb9bj2 
max height allows to change the height by mouse drag. 
**Request a new feature where auto height automatically increases height if the height is within the max height limit** 

Example
1) initial grid height in dialog - 400 px (dialog height should be 400)
2) Expand a record - change the height of dialog to 500px
3) Expand 5 records - fix the height of dialog to 600px (becuase that is the max height limit) and provide vertical scroll bar.

jqxgrid inside jqxwindow - with autoheight true of jqxgrid -  dialog does not show any scroll bar and data records are hidden

**Comment by jqwidgets** [comment]
Hello,

Thank you for the feature request.
I would like to suggest you change **[jqxWindow](https://www.jqwidgets.com/jquery-widgets-documentation/documentation/jqxwindow/jquery-window-api.htm?search=window)** size depends on the **[jqxGrid](https://www.jqwidgets.com/jquery-widgets-documentation/documentation/jqxgrid/jquery-grid-api.htm?search=grid)** size.
For this purpose, you could bind to the _"**onRowexpand**" event_.
We will think about this option.

Best Regards,
Hristo Hristov

jQWidgets team
https://www.jqwidgets.com
