### ISSUE TITLE
Feature Request: Max height limitation for jqxgrid with autoheight

### ISSUE THREAD

**Issue by jvutukur** [jqwidgets/jQWidgets#109]
<jqxGrid [theme]="'material'" #myGrid
    [width]="100%" autoheight=true  **[maxheight]="500"**  [source]="employeesAdapter" [columns]="columns" 
    [rowdetails]="true" [rowsheight]="35" [initrowdetails]="initRowDetails"
    [ready]="ready" [rowdetailstemplate]="rowdetailstemplate">
</jqxGrid>

Autoheight upto 500 and after 500 bring a scroll bar

**Comment by jqwidgets** [comment]
Hello,

Thank you for the suggestion.
We will discuss this.

Best Regards,
Hristo Hristov

jQWidgets team
https://www.jqwidgets.com
