### ISSUE TITLE
jqxDateTimeInput: vue jqxDateTimeInput error occured from 7.2.0

### ISSUE THREAD

**Issue by EnochG1** [jqwidgets/jQWidgets#122]
Hi, when I update from 7.1.0 to 7.2.0, value type in vue_jqxdatetimeinput.vue error occured like below.

![image](https://user-images.githubusercontent.com/19601207/57120850-f8f42e00-6dae-11e9-93fc-9cfd48bd921f.png)

I think Null should be null or other type.

thanks

**Comment by bmarkov** [comment]
We are aware of that. As a workaround, replace Null with null

**Comment by EnochG1** [comment]
Temporary I downgraded to 7.1.0. Thanks
