### ISSUE TITLE
[vue] jqx widget makes html elements duplicate in vue-router

### ISSUE THREAD

**Issue by EnochG1** [jqwidgets/jQWidgets#124]
continue from https://github.com/jqwidgets/jQWidgets/issues/123

Hi, thank you for your fast reply and I think there's still problem in vue-router(I think not only in vue but in SPA) environment.

Some of jqWidgets components(Not all, because like jqxButton) are append Popup element, just append at the end of body tag. But using vue-router, they makes duplicated element when that component has loaded.

![image](https://user-images.githubusercontent.com/19601207/57136422-c4509880-6de7-11e9-84e9-5b24519cb326.png)
(div elements in orange box are not usual but still in page)

With SPA like screenshot, we can access Home and About without refresh browser page and vue makes it with vue-router. But the way you append popup element makes page disaster. I think even though that div element is needed for your component, it should be append inside of parent div(like div class="about") then it can removed when routing component is changed.

Below screenshot is when sample app was clicked Home > About > Home > About.
![image](https://user-images.githubusercontent.com/19601207/57136849-07f7d200-6de9-11e9-9336-007b2f5e5ebd.png)
![image](https://user-images.githubusercontent.com/19601207/57136857-0b8b5900-6de9-11e9-9f81-246cfd8f8fec.png)
![image](https://user-images.githubusercontent.com/19601207/57136861-0dedb300-6de9-11e9-878b-7b8844eb8bda.png)
![image](https://user-images.githubusercontent.com/19601207/57136864-10500d00-6de9-11e9-993f-7a6885ace271.png)

I just create project with @vue/cli(https://cli.vuejs.org/) and just added jqxButton in home and jqxComboBox component referring your demo page.

Thank you

**Comment by jqwidgets** [comment]
It cannot be part of the element”s tag because it is overflow:hidden

**Comment by EnochG1** [comment]
The Problem is NOT if tag is overflow: hidden or display:none;.
I think you should handle when the parent tag is destroyed.
The element which has "aria-owns" and you created "id" is matching.
But even though element which has aria-owns destroyed, the element you created still remains.
And it remains until the browser page is refreshed.
BUT SPA(Single Page Application) is not refreshing when menu moves on so I pointed this is problem. Because menu is changed, routing area is changing but your div elements are still remaining.

**Comment by bmarkov** [comment]
When you call the 'destroy' method of an element, it removes all elements it owns. It's not automatically done, it is done when you call the method.
