### ISSUE TITLE
[vue][Question] How Can I use jqwidgets if I buy commercial version.

### ISSUE THREAD

**Issue by EnochG1** [jqwidgets/jQWidgets#141]
Hi,
Following to jQWidgets homepage, for using vue version (https://www.jqwidgets.com/vue-components-documentation/index.htm) I had to use jQWidgets with npm which is free version.

But what if I want to use vue version with commercial version? (I didn't purchase yet but I would to)
I think npm can't provide commercial version but I couldn't find help guide to using vue version without package manager.
I tried to set local, but just using vue with .js files, the error message occured in jqxcore.js.

Also, isn't there anyway to use jQWidgets package without jqx-all.js?
I think npm version of jqwidgets-scripts makes webpack build slow. Because even though I'm not using all of jQWidgets components but using just jqxgrid, package.json(in jqwidgets-scripts) watching main as jqx-all.js and there's no any node build in jqwidgets-scripts itself.
So vue version can't run in IE11 if I'm not using babel-loader to /node_modules/jqwidgets-scripts.

**Comment by bmarkov** [comment]
The npm package can be unlocked using a javascript license key. Our  Vue components run in IE11 when they are packaged with ES5 bundles. Our current online Demo bundles are with ES6 which require a modern web browser.

**Comment by EnochG1** [comment]
OK, thanks :)
