### ISSUE TITLE
[vue][jqxGrid] Best way to make custom editing cells

### ISSUE THREAD

**Issue by EnochG1** [jqwidgets/jQWidgets#142]
Hi, I have question about custom editing in jqxGrid.
I searched your guides like [custom editor](https://www.jqwidgets.com/vue/vue-grid/#https://www.jqwidgets.com/vue/vue-grid/vue-grid-customcolumneditor.htm), it seems I can use only with edit components by yours like jqxInput, jqxSlider, jqxDropDownList, etc.

My customer needs various edit format like belows, and I need create this and get value from each cells, using vue components preffered. What is best way to implement this with jqxgrid vue component? Is there any sample for it?

1. input with search in cell : press search button, modal window opened and search DB and select data in modal, data will be bind in input. Also input value can modified by keyboard input.
![image](https://user-images.githubusercontent.com/19601207/58929897-16dcf600-8794-11e9-8a5a-19b0faa6d381.png)

2. multi date UI : press + button, another input element added. press trash button one input element deleted.
![image](https://user-images.githubusercontent.com/19601207/58930001-aedadf80-8794-11e9-87d6-d6f0f20ebecf.png)

I'm just giving you some example of requirements but point is want to put multi elements in each cell (or columns), and if I can, I want to just provide editor with my Vue Components.

**Comment by jqwidgets** [comment]
Hello EnochG1,

Thank you for contacting us.
I will try to suggest you a few things but it will be better if you could provide us with more details.
What you want to achieve and what is your final goal?
Is this a always visible components or only in the edit mode?
If I refer to the title then the suitable option is to use the approach below with _"**columntype: 'custom'**" member_ of the _"**columns**" property_:
https://www.jqwidgets.com/vue/vue-grid/vue-grid-customcolumneditor.htm?light
This approach could be used to create a different widgets depends on case.
The _"**createeditor: (row, cellvalue, editor, cellText, width, height)**" callback_ could be used to add more widgets on the same cell.
You could append new _divs_ for the additional components and to use the presented approach.

Best Regards,
Hristo Hristov

jQWidgets team
https://www.jqwidgets.com

**Comment by EnochG1** [comment]
Hi,
My goal is for edit mode, but also for search.
If I press search button it must be shown like screenshot(in input), but it also be modified. (we have save button)
when I saw your example using creatededitor, it seems to be only available with your widget editors like
`
createeditor: (row, cellvalue, editor, cellText, width, height) {
editor.jqxDropdown(options);
// or
editor.jqxInput(options);
// or
editor.jqxSlider(options);
}
`
but like upper UI, I have to implement it without your jqxWidget.
And actually, cause I'm using vue, editor.jqxWidget(options) seems to be so jQuery-liked.
I prefer inject Vue Instance, but if I can't, at least we need the way to inject editor html and element ID? or other way.

**Comment by jqwidgets** [comment]
Hello EnochG1,

You could try to append the new HTML element into the _"**editor**"_ and after that to use initialization of your UI component.
But I would like to mention that we cannot guarantee the final result if you do not use our components.
Also, you could try to use and the _"**cellsrenderer**" callback_ but it expects to return a string.
You should re-initialize if you make some updates there, too.

Best Regards,
Hristo Hristov

jQWidgets team
https://www.jqwidgets.com
