### ISSUE TITLE
jqxScheduler - "exactTime" with a small interval of time it causes inappropriate behavior

### ISSUE THREAD

**Issue by jqwidgets** [jqwidgets/jQWidgets#144]
It could be tested with these date/time settings:
```javascript
  start: new Date(2017, 10, 23, 11, 1, 0),
  end: new Date(2017, 10, 23, 11, 6, 0)
```

**Example:**
https://jsfiddle.net/x9tsmuo2/

**Comment by jqwidgets** [comment]
cannot reproduce

**Comment by spridivirajan** [comment]
Hello,

Can you try with JSFiddle provided in the work item request?
**https://jsfiddle.net/x9tsmuo2/**

Please use the below start and end time to reproduce the issue. It is very clear that appointment is not displaying in the jqxScheduler widget.
  **start: new Date(2017, 10, 23, 11, 1, 0) 
  end: new Date(2017, 10, 23, 11, 6, 0)** 

Mr. Hristo Hristov tried this sample and then only Hristo Hristov had created work item for the reported issue.

Please see the attached image for reference.

![Issue-No Data Disply](https://user-images.githubusercontent.com/52660461/60808583-4c676b80-a1a6-11e9-8f38-694b765ad4fc.PNG)

**Comment by jqwidgets** [comment]
The solution is to change the scale to fiveMinutes
