### ISSUE TITLE
jqxNumberInput - when using "symbol" property with more than one symbols the caret will move

### ISSUE THREAD

**Issue by jqwidgets** [jqwidgets/jQWidgets#145]
Use the arrows buttons of the **_jqxNumberInput_**.

**Example:**
http://jsfiddle.net/txhi/4Lm10fh8/

**Topic:**
https://www.jqwidgets.com/community/topic/caret-is-moving-if-symbol-has-more-than-1-char/

**Comment by bmarkov** [comment]
Suggestion: https://www.htmlelements.com/demos/numerictextbox/overview/
