### ISSUE TITLE
Ivy Compile - ERROR in Cannot find module 'xxxxx/jqwidgets-scripts/jqwidgets-ng/jqwidgets-scripts/jqwidgets/jqxcore'

### ISSUE THREAD

**Issue by Robbyn666** [jqwidgets/jQWidgets#148]
Hello, when compiling with Ivy I get the following error:

ERROR in Cannot find module '/Users/Robbyn/Documents/PhpstormProjects/pressmind_pagina/node_modules/jqwidgets-scripts/jqwidgets-ng/jqwidgets-scripts/jqwidgets/jqxcore'

My tsconfig.ts:

`{
  "compileOnSave": false,
  "compilerOptions": {
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es5",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": ["es5", "es6", "dom"]
  },
  "exclude": ["dist", "src", "app-builds", "node_modules"],
  "include": [
    "src/**/*"
  ],
  "files": [
    "node_modules/jqwidgets-scripts/jqwidgets-ts/angular_jqxgrid.ts",
    "node_modules/jqwidgets-scripts/jqwidgets-ts/angular_jqxtabs.ts",
    "node_modules/jqwidgets-scripts/jqwidgets-ts/angular_jqxinput.ts",
    "node_modules/jqwidgets-scripts/jqwidgets-ts/angular_jqxdropdownlist.ts",
    "node_modules/jqwidgets-scripts/jqwidgets-ts/angular_jqxmenu.ts",
    "node_modules/jqwidgets-scripts/jqwidgets-ts/angular_jqxpopover.ts",
    "node_modules/jqwidgets-scripts/jqwidgets-ts/angular_jqxcalendar.ts",
    "node_modules/jqwidgets-scripts/jqwidgets-ts/angular_jqxdatetimeinput.ts",
    "node_modules/jqwidgets-scripts/jqwidgets-ts/angular_jqxnumberinput.ts",
    "node_modules/jqwidgets-scripts/jqwidgets-ts/angular_jqxvalidator.ts",
    "node_modules/jqwidgets-scripts/jqwidgets-ts/angular_jqxtooltip.ts"
  ],
  "angularCompilerOptions": {
      "enableIvy": true
  }
}
`
Am I doing something wrong?
The error message appears during Prod compilation as well as in Dev compilation.

Regards
Robbyn

**Comment by jqwidgets** [comment]
Hello Robbyn666,

Thank you for contacting us.
I would like to mention that the _"Ivy Compile"_ is not supported.
Officially the stable state will be available with **Angular 9**.
Thank you for this feedback and we will care about this in the future if this still persists.

Best Regards,
Hristo Hristov

jQWidgets team
https://www.jqwidgets.com

**Comment by Robbyn666** [comment]
oh ok, all right. Thanks for the info.

regards
Robbyn
