### ISSUE TITLE
jqxScheduler - "exactTime" with a small interval of time it causes inappropriate behavior. Also, It is not displaying all the further appointments if one appointment has small duration.

### ISSUE THREAD

**Issue by spridivirajan** [jqwidgets/jQWidgets#155]
Hello,

Can you try with below JSFiddle provided?
https://jsfiddle.net/x9tsmuo2/

Please use the below start and end time to reproduce the issue. It is very clear that appointment is not displaying in the jqxScheduler widget.
start: new Date(2017, 10, 23, 11, 1, 0)
end: new Date(2017, 10, 23, 11, 6, 0)

Mr. Hristo Hristov tried this sample and then only Hristo Hristov had created below work item for the reported issue.
Work Item Request: https://github.com/jqwidgets/jQWidgets/issues/144

Please see the attached image for reference.
![Issue-No Data Disply](https://user-images.githubusercontent.com/52660461/60808994-31e1c200-a1a7-11e9-91e3-486d25bf84dd.PNG)

**Comment by spridivirajan** [comment]
Why are you closing the issue without solving it? This is not at all correct.

**Comment by jqwidgets** [comment]
The solution is already posted. The interval should be set to fiveMinutes, not tenMinutes.
