### ISSUE TITLE
Nuget Package is not usable for development. 

### ISSUE THREAD

**Issue by tumbledwyer** [jqwidgets/jQWidgets#160]
The nuget package is not usable because of the enormous amount of files in it.  I'm sitting and waiting for the package install to complete and it's at over 8000 files downloaded and still going. This contains, what looks like, the entire repo, including demo files.

Could you not split the nuget package into the various parts for each of the frameworks you support so it can be used in dev? So jqGrid for React etc etc.

Otherwise it seems the only way to use the files is to download and paste them into your solution. It's 2019, surely we can use a package manager for this.

**Comment by jqwidgets** [comment]
The newest package is just 7MB  and does not include demos. The link to it is https://www.nuget.org/packages/jQWidgets_Framework/8.1.4
