### ISSUE TITLE
jqxTabs - initTabContent not called if a tab is removed

### ISSUE THREAD

**Issue by qadram** [jqwidgets/jQWidgets#162]
If you use initTabContent to get called when a tab is selected for the first time, if you remove a tab, for example, by closing it because showCloseButtons is true, initTabContent won't get called.

It can be reproduced on the demo here:
[https://www.jqwidgets.com/react/react-tabs/index.htm#https://www.jqwidgets.com/react/react-tabs/react-tabs-closebuttons.htm]
- Modify that demo to add a function for initTabContent
- It will work every time you add a tab
- But if you close any of them and try to create a new one, it won't get called

I have been checking the source code and it looks the internal array _initTabContentList to store the tabs that have been initialized it never gets set to false for the tab that is removed.

**Comment by jqwidgets** [comment]
Hello qadram,

Thank you for this scenario that you provide and for this feedback.
Meanwhile, I would like to suggest you try to bind to _"**tabclick**" event_ to recognize on which tab is clicked.

Best Regards,
Hristo Hristov

jQWidgets team
https://www.jqwidgets.com

**Comment by jqwidgets** [comment]
Fixed in 8.3.1
