### ISSUE TITLE
jqxSplitter can't use in CORS iframe

### ISSUE THREAD

**Issue by kiuru** [jqwidgets/jQWidgets#164]
I'm running website (app1.example.com) which keeps inside iframe (app2.example.com) and I'm using **jqxSplitter** on that iframe. I found that jqxSplitter calls `window.top` which is on my situation iframe's parent site. This website and iframe is running on different Origins (app1.example.com and app2.example.com) which means that command `window.top` violate browser's Cross-Origin-Policy, because the top site is iframe's parent website. That why it gives an following error:

	Uncaught DOMException: Blocked a frame with origin "https://app2.example.com" from accessing a cross-origin frame.

And the line which in the end affect this error:

![image](https://user-images.githubusercontent.com/3456027/62005475-8cce5f80-b13c-11e9-87b9-490b846e00b2.png)

Could you somehow change this line of code another one, which accept running jqxSplitter in iframe if they located in different Origins?

Microsoft have a guidance, which tells to avoid using `window.top` in applications:
[https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/best-practices/business-logic/avoid-window-top](https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/best-practices/business-logic/avoid-window-top)

**Comment by jqwidgets** [comment]
The code is added by design. However, we will consider your suggestion in future versions.
