### ISSUE TITLE
jqxScheduler - daily recurring appointment shows in the wrong range

### ISSUE THREAD

**Issue by jqwidgets** [jqwidgets/jQWidgets#169]
It shows one day less if you enter a new appointment there with the same range.
**_Important:_** Needs to change the color on the next entered appointment.

**Topic:**
https://www.jqwidgets.com/community/topic/daily-recurring-appointment-shows-1-less-day/

**Comment by zeeshu33** [comment]
Hi JqWidgets Team,

Thanks for fixing this issue. May I ask when will it be Released?

**Comment by jqwidgets** [comment]
Hi, According to our devs the issue is resolved in 8.2.0 release.

**Comment by zeeshu33** [comment]
Hi,

Thanks for the quick response but I am still able to reproduce this issue in the 8.2.0 Release.

And this was not mentioned in the Release notes of 8.2.0 as well. Thanks.


Regards,
Zeeshan

**Comment by zeeshu33** [comment]
Hi,

Can you kindly provide an update on this?

Regards,
Zeeshan Ahmed

**Comment by jqwidgets** [comment]
The issue is resolved.

**Comment by zeeshu33** [comment]
Hi,

I know but it is not resolved in the 8.2.0 Release. Will it be available in the next Release?

**Comment by zeeshu33** [comment]
Hi Jqx Team,

Sorry to bother you again but I really need to know that when this issue will be Released?

We will be buying the Enterprise license once we see it as fixed. Thanks.

Regards,
Zeeshan

**Comment by jqwidgets** [comment]
Hi Zeeshan,

You can already check online through jsfiddle, jseditor or codepen the fix. The new 8.3.2 version will be released today.

**Comment by zeeshu33** [comment]
Awesome... Big Thanks.
