### ISSUE TITLE
Urgent : jqxgrid nested grid filtered error

### ISSUE THREAD

**Issue by Defcoq** [jqwidgets/jQWidgets#179]
Hi,
I have a strange problem with nested jqxgrid. the parent grid is load correctly, the child nested grid also.. but only on the first load. child grid is loading data locally from the parent and parent is getting data from REST call in virtual mode. when trying to filtered the master grid, I always got this strange error and the grid wich make the nested grid  stop working :
**jqxgrid.filter.js:8 Uncaught Error: jqxGrid: The data is still loading. When the data binding is completed, the Grid raises the 'bindingcomplete' event. Call this function in the 'bindingcomplete' event handler.
    at c.<computed>.showrowdetails (jqxgrid.js:8)
    at c.<computed>._postrender (jqxgrid.js:8)
    at c.<computed>.applyfilters (jqxgrid.filter.js:8)
    at c.<computed>._applyfilterfromfilterrow (jqxgrid.filter.js:8)
    at HTMLInputElement.<anonymous> (jqxgrid.filter.js:8)
    at HTMLInputElement.dispatch (jquery-3.2.1.min.js:3)
    at HTMLInputElement.q.handle (jquery-3.2.1.min.js:3)**

I'm using the latest latest version.... but in the old version (3.7.1) this is working...
is it a bug? or I'm doing something wrong... help me please. see the attachment bellow with a snippet of code that describe the problem
thank you so much
regards
[Nested_Grid_Error_Example.zip](https://github.com/jqwidgets/jQWidgets/files/3555698/Nested_Grid_Error_Example.zip)

**Comment by jqwidgets** [comment]
Hello Defcoq,

Thank you for the [feedback](https://github.com/jqwidgets/jQWidgets/issues/180).
We create a work item for this case.
Also, there is a similar [discussion](https://www.jqwidgets.com/community/topic/urgent-jqxgrid-nested-grid-filtered-error/#post-106641) in our forum with a suggestion.

Best Regards,
Hristo Hristov

jQWidgets team
https://www.jqwidgets.com
