### ISSUE TITLE
jqxForm - when more than one jqxForm-s on page, dropdown list opens only in last form

### ISSUE THREAD

**Issue by jqwidgets** [jqwidgets/jQWidgets#181]
When we have more than one jqxForm on the page with jqxDropDownList in them,
only the droodown lists in the last form could be opened.

Example: http://jsfiddle.net/zqsfock5/

**Comment by fboller** [comment]
Hi, any updates on this? I am current experiencing the same issue. Any help you can provide me would be highly appreciated.

**Comment by jqwidgets** [comment]
We will fix it for our June's release

**Comment by jqwidgets** [comment]
Related issue is: https://github.com/jqwidgets/jQWidgets/issues/266

**Comment by fboller** [comment]
Thanks!

**Comment by jqwidgets** [comment]
Fixed in 9.1.5
