### ISSUE TITLE
jqxTabs - Close tabs when added dynamically

### ISSUE THREAD

**Issue by archierinn** [jqwidgets/jQWidgets#206]
After add a new tab, if I want to close the new added tab - incorrect closing of the chosen tab. (usually first tab closed instead the new added tab). I check at 8.2.0 version in demo page is working, but after update 8.3.2 not working.

Example:
http://jsfiddle.net/khsf5a1d/

**Comment by jqwidgets** [comment]
Hello ArchieRinn,

Thank you for contacting us and for this feedback.
Also, I will include one more example:
http://jsfiddle.net/2soL9fg4/

Best Regards,
Hristo Hristov

jQWidgets team
https://www.jqwidgets.com

**Comment by jqwidgets** [comment]
Additional case with closing of the incorrect tab.
**Example:**
http://jsfiddle.net/075ace8d/

**Topic:**
https://www.jqwidgets.com/community/topic/closing-the-first-tab-instead-of-one-where-close-button-have-been-pressed

**Comment by jqwidgets** [comment]
Fixed for ver. 9.0.0
