### ISSUE TITLE
How to use NPM to install the Vue module of jqwidgets scripts？

### ISSUE THREAD

**Issue by chensimin09** [jqwidgets/jQWidgets#208]
Because the whole jqwidgets scripts is too large (including ng / react, etc.), I don't want so many. Even I want a component of the Vue module, such as jqxgrid. Therefore, I want to know how to use NPM to install the Vue module of jqwidgets scripts, or a component of the Vue module, such as jqxgrid.

**Comment by jqwidgets** [comment]
Please, refer to: https://www.jqwidgets.com/vue-components-documentation/
