### ISSUE TITLE
JQWidgets React Documentation Update Request

### ISSUE THREAD

**Issue by 5lineofcode** [jqwidgets/jQWidgets#239]
Please, add Api Reference tab in JQWidgets React documentation.

<img width="959" alt="Screen Shot 2020-01-23 at 16 12 50" src="https://user-images.githubusercontent.com/43805298/72970957-4b70f100-3dfb-11ea-97a2-bb08fde0fae7.png">

**Comment by bmarkov** [comment]
The documentation with API refs is here: https://www.jqwidgets.com/react-components-documentation/

**Comment by 5lineofcode** [comment]
@bmarkov thanks !!
