### ISSUE TITLE
How can i remove multi items at once

### ISSUE THREAD

**Issue by GuDuJian-J-Zhang** [jqwidgets/jQWidgets#24]
Thanks,
How can i remove multi items at once, like this:
![image](https://user-images.githubusercontent.com/21232983/50336417-1be11c80-0549-11e9-8da9-b02929ee7dd3.png)

**Comment by bmarkov** [comment]
You can remove them item by item by using the Tree's removeItem method. Please, refer to: https://www.jqwidgets.com/jquery-widgets-documentation/documentation/jqxtree/jquery-tree-api.htm to see how to use the method.

**Comment by GuDuJian-J-Zhang** [comment]
@bmarkov 
Thanks for you response.
But if i have many items to remove, "**remove them item by item**"  maybe too slow.
I mean the browser will be crash if i remove item by item.
Is there any method to remove quickly?

**Comment by bmarkov** [comment]
As far as I know, there is no method in the Tree component that removes multiple items with just one method call.
