### ISSUE TITLE
Feature Request - RowRenderer

### ISSUE THREAD

**Issue by CXXXV** [jqwidgets/jQWidgets#247]
It is common for an app to need row highlight based on the value of one cell. Currently we have to use the cellclassname callback on each cell. This makes loading of the grid very slow.

We know that this CSS manages the background of the whole row.

```
 .jqx-grid-cell-selected {
    background:blue !important;
}
```

We also know that behind the scenes jqxGrid already supports row highlighting as evidenced by clicking on a row and the row highlights.

What I would like to have is RowRenderer with data and row attributes. So  that code would be like this:

```
   renderrow: function (row, data){

     if (data == X){
       row.background-color = red;
    }
  }
```

In standard HTML this works with a table :

```
I was able to partially achieve the row highlight as follows:

```
.complete .jqx-grid-cell-selected {
    background:blue !important;
}
```
and:

```
$('#transGrid').on('rowclick', function (event) {	
	
	  $(this).addClass('complete');

})

```

If some one can tell me how to trigger this within cellclassname callback then we might have something.

**Comment by jqwidgets** [comment]
cellsrenderer can be used for highlighting a row is the cellsrenderer is used for all columns in a Grid. Ex with cellsrenderer: https://www.jqwidgets.com/jquery-widgets-demo/demos/jqxgrid/defaultfunctionality.htm?light

**Comment by CXXXV** [comment]
You missed the point. Cellrender requires the code on every cell. That makes it very slow.

What I am asking for is a function that uses rowindex. Like so:

jqxgrid.rowhighlight(_rowindex)_

The code to select which row is independent of the cell.
