### ISSUE TITLE
jqxGrid - keyboard navigation between groups broken when showgroupaggregates == true

### ISSUE THREAD

**Issue by Slokken** [jqwidgets/jQWidgets#249]
When navigating downwards in grouped grid, the expected behavior is that the selected cell skips to next group when reaching bottom of group. When showgroupaggregates is activated, the grid instead scrolls to top, and no cell is selected.

**Example:**
https://jsfiddle.net/vp3b6zt0/

**Comment by jqwidgets** [comment]
Fixed for 9.1
