### ISSUE TITLE
jqxPasswordInput - when clearing the password input field, it shows a wrong "placeHolder"

### ISSUE THREAD

**Issue by jqwidgets** [jqwidgets/jQWidgets#270]
**Example:**
https://www.jqwidgets.com/jquery-widgets-demo/demos/jqxpasswordinput/defaultfunctionality.htm?light

**Comment by LuizHenriqueBK** [comment]
Same error in jqxScheduler, in css themes found 
`input[type="password"] {
    letter-spacing: 0.3em;
}`
