### ISSUE TITLE
TreeView - html in node breaks element

### ISSUE THREAD

**Issue by nightrider77** [jqwidgets/jQWidgets#271]
Hello.

If I have only `Home` text in node, everything is ok.
If I add `<i class="home icon"></i>` (or any other html) to node, its inner html becomes as following:

`Home id="jqxWidget_generated_id" <i class="home icon"></i> Home`

As if scripts
1. Removes all html from original element
2. Adds id tag
3. Inserts content from 1 and 2 step to element's inner html start.

Why?

Thanks in advance.

Just Home text:
![2020-05-09_15-25-14](https://user-images.githubusercontent.com/20248492/81504686-6193b600-92f3-11ea-9ca8-bbafd8aaace2.png)

Add html:
![2020-05-09_15-26-21](https://user-images.githubusercontent.com/20248492/81504685-60628900-92f3-11ea-9ed7-3867026a1b28.png)

**Comment by bmarkov** [comment]
This can be managed by using a span or div tag and putting the 'i' and text content inside it
