### ISSUE TITLE
jqxNumberInput and localization

### ISSUE THREAD

**Issue by MyemaHMN** [jqwidgets/jQWidgets#278]
**Describe the bug**
jqxNumberInput does not use the Comma key on the keyboard as a decimal separator. 
Using the widget in European  context needs the comma as decimal separator. You can set this using the decimalSeparator property. Comma is shown in the widget. However, if you type in 1,23 on the keyboard (not on the numpad), the comma is not used as seperator. You still have to type in 1.23. This is irritating. 
This is because the keyboard codes are hardcoded in the jqxNumberInput.js. It reads:
if(v==188||v==110) ... 
188 is the Code for Period, 110 for NumpadDecimal. 

**To Reproduce**
1. Setup a jqxNumberInput Widget with:
  [decimalSeparator]="','"
2. Type in "1,23", (not on the numpad) which should be shown as 1,23 in the widget.
3. It shows as 123,00

**Comment by bmarkov** [comment]
Behavior is improved for next release.
