### ISSUE TITLE
how to use this component in antd design pro ?

### ISSUE THREAD

**Issue by ssf2015** [jqwidgets/jQWidgets#28]
hello ,I want to use this component in our project, but our project is used by antd design pro ,I tried a lot of ways to configure webpack， But still doesn't work， Can you help me? I am going crazy.

**Comment by jqwidgets** [comment]
Hello,

Could you provide us with more details, which component exactly you mean?
I would like to suggest you look at our **demos** [page](https://www.jqwidgets.com/jquery-widgets-demo/).
You could find a lot of useful information.

Best Regards,
Hristo Hristov

jQWidgets team
http://www.jqwidgets.com

**Comment by ssf2015** [comment]
I use create-react-app to creat a application ,it also doesn't work,here is detail .
![image](https://user-images.githubusercontent.com/15663926/50754068-53f99680-128f-11e9-8ea0-3467ef2a974b.png)

**Comment by ssf2015** [comment]
I did it according to official instructions.
 
![image](https://user-images.githubusercontent.com/15663926/50754130-93c07e00-128f-11e9-95f3-fa2dd7ff8734.png)

**Comment by ssf2015** [comment]
> Hello,
> 
> Could you provide us with more details, which component exactly you mean?
> I would like to suggest you look at our **demos** [page](https://www.jqwidgets.com/jquery-widgets-demo/).
> You could find a lot of useful information.
> 
> Best Regards,
> Hristo Hristov
> 
> jQWidgets team
> http://www.jqwidgets.com

and this is my webpack.json
![image](https://user-images.githubusercontent.com/15663926/50757462-52819b80-129a-11e9-8532-435ebaae0f42.png)
