### ISSUE TITLE
Vertical scrollbar for jqxscheduler timeline view

### ISSUE THREAD

**Issue by AnaidaRashmi** [jqwidgets/jQWidgets#280]
I want to add vertical scrolling for jqxscheduler in timeline view. Tried with adding `height: auto` not getting how to add height dynamically based on number of appointments. I have huge number of appointments to be shown on scheduler. Showing appointments on selecting little arrows is not a proper solution for my requirement. I tried without giving height but no use. Please help. I am using angular-8 for development.

**Comment by bmarkov** [comment]
Hi AnaidaRashmi,

Unfortunately, this functionality cannot be achieved with our Scheduler component.  We are working hard on its next version and will make sure to have support for that.

**Comment by AnaidaRashmi** [comment]
Hi,

I got the solution for this problem. Since jqxScheduler uses jqxGrid table
internally to accommodate the data, we have to provide height and scrollbar
for grid as shown below:
.jqx-grid-table {
    height: 3000px !important;
    overflow-y: scroll !important;
}
height value as required. Hope this helps someone.
Thanks for your support.

Regards,
Priyanka Mulagund,
L and T Technology Services
