### ISSUE TITLE
jqxGrid - format date records from a string is not appropriate

### ISSUE THREAD

**Issue by jqwidgets** [jqwidgets/jQWidgets#281]
When trying to filter for a value that is entered as a string it is not filtered appropriately.

**Example:**
https://jsfiddle.net/69n78uxg/

**Topic:**
https://www.jqwidgets.com/community/topic/grid-filterrow-date-format

**Comment by bmarkov** [comment]
The DataGrid is not initialized correctly. dataField is set, but dataFields is expected.
