### ISSUE TITLE
lots of vars called <label></label instead of <label></label> ( forgot a > ?)

### ISSUE THREAD

**Issue by fabriceBruchon** [jqwidgets/jQWidgets#291]
I Found 33 times in the library the occurence of : <label></label without the ending ">"

It seams that you forgot it, no ???

**To Reproduce**
just do a general search of the : string "<label></label " to find the 33 occurences : 

for example in jqxcombobox.js, line 274 :
```
var label = $(“<label></label”);
if (this.hint) {
label[0].innerHTML = this.placeHolder;
}
```

**Comment by bmarkov** [comment]
Fixed for next release
