### ISSUE TITLE
jqxScheduler - when trying to click on the current day (today) it does not react from the calendar

### ISSUE THREAD

**Issue by jqwidgets** [jqwidgets/jQWidgets#295]
**Example:**
https://www.jqwidgets.com/jquery-widgets-demo/demos/jqxscheduler/defaultfunctionality.htm?light

**Comment by bmarkov** [comment]
Works Ok in the current version. The view should not contain the Today date, otherwise, it will navigate to the same view and there will be no visible result for the user in the Scheduler
