### ISSUE TITLE
jqxNumberInput - when using the "decimalSeparator" property with the "," option it set inappropriate value with the "val" method

### ISSUE THREAD

**Issue by jqwidgets** [jqwidgets/jQWidgets#307]
**Example:**
http://jsfiddle.net/y5b03doe/1/

**Comment by MyemaHMN** [comment]
Same in Angular: Using jqxNumberInput with [decimalSeparator]="','" and then assign a decimal value with jqxNumberInput.val(3.21) causes a NaN - Error.
This seems to be a bug. 
See: https://angular-ivy-zyfi9g.stackblitz.io
Important to fix!!!

**Comment by MyemaHMN** [comment]
We discovered: you can use getDecimal and setDecimal instead. Both functions are not appropriately documented in the documentation, however.

**Comment by bmarkov** [comment]
Fixed for next release
