### ISSUE TITLE
jqxDataAdapter (FireFox) - cannot format the date appropriately when has comma ("," symbol)

### ISSUE THREAD

**Issue by jqwidgets** [jqwidgets/jQWidgets#309]
**Example:**
https://jsfiddle.net/fyu1mdv7/

**Comment by bmarkov** [comment]
Requires setting the datafield's format property to something like: 'format: "MM/dd/yyyy, hh:mm:ss"'

**Comment by kapalkat** [comment]
Hey @bmarkov this date is coming from standard JS function toLocaleString.
Please test the following
test = new Date();
test.toLocaleString()
Example of output: "9/2/2020, 2:27:37 PM"
I think this is the most popular way to handle date based on browser locale so I do not agree that we should now parse this string and adjust for jqWidgets lib!

**Comment by bmarkov** [comment]
Hi kapalkat,

You have to either provide a Date object or Parse the Date object. This is how this works.

**Comment by bmarkov** [comment]
Example:   { "name": "end_time", "type": "date", format: 'dd/MM/yyyy, hh:mm:ss.z tt' }

**Comment by kapalkat** [comment]
Got it! Works fine when I provide format prop.
