### ISSUE TITLE
Row data with 'group' as key does not load any data.

### ISSUE THREAD

**Issue by rsantoshreddy** [jqwidgets/jQWidgets#312]
**Describe the bug**
In row data if we have group as key, grid is loading no data. 

**To Reproduce**
Please check code at https://github.com/rsantoshreddy/jqxGridIssue

**Expected behavior**
It should work for any key of data.

**Screenshots**
![image](https://user-images.githubusercontent.com/6243528/89574240-74158100-d849-11ea-8eda-b2f88d6c51aa.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by bmarkov** [comment]
'group' is a keyword used by jqxGrid. You can use the dataAdapter's map property in order to bind to your dataSource's group property, but for the Grid, the 'map' field will be used.
