### ISSUE TITLE
jqxNumberInput decimalSeparator and groupSeparator not properly working

### ISSUE THREAD

**Issue by MyemaHMN** [jqwidgets/jQWidgets#323]
The decimalSeparator-setting has been improved since issue # 278. Thank you. With decimalSeparator= ',' you can now use the comma on the keyboard to jump to the decimals. However: This is not working in combination with groupSeparator. As soon as you define a groupSeparator, you still only can use a period to jump to the decimal part.

**Comment by bmarkov** [comment]
Fixed for next release
