### ISSUE TITLE
Requires setting the datafield's format property to something like: 'format: "MM/dd/yyyy, hh:mm:ss"'

### ISSUE THREAD

**Issue by kapalkat** [jqwidgets/jQWidgets#327]
Requires setting the datafield's format property to something like: 'format: "MM/dd/yyyy, hh:mm:ss"'

_Originally posted by @bmarkov in https://github.com/jqwidgets/jQWidgets/issues/309#issuecomment-685656520_

Hey @bmarkov this date is coming from standard JS function toLocaleString.
Please test the following
test = new Date();
test.toLocaleString()
Example of output: "9/2/2020, 2:27:37 PM"
I think this is the most popular way to handle date based on browser locale so I do not agree that we should now parse this string and adjust for jqWidgets lib!

Full description of the problem is under:
https://www.jqwidgets.com/community/topic/wrong-date-generated-from-local-data-in-firefox/#post-112929
Provided workaround does not work!
Example:
https://jsfiddle.net/kapalkat/vmcgfL18/3/

**Comment by bmarkov** [comment]
The correct format should be set. Otherwise it will not work as such date cannot be parsed with new Date.

**Comment by bmarkov** [comment]
Ex:  { "name": "end_time", "type": "date", format: 'dd/MM/yyyy, hh:mm:ss.z tt' }

**Comment by kapalkat** [comment]
But creating date object from locale works fine in every browser:
![ToDateFromLocale](https://user-images.githubusercontent.com/26725074/91984184-6bbb4380-ed2c-11ea-8d14-19fb34ffe8cd.png)

**Comment by bmarkov** [comment]
Hi kapalkat,

This is a misconfiguration. The DataGrid Date column works with Date objects, not with Strings. If you want to populate a Date column with Strings, these strings should be parsed. In order to parse correctly the Strings, you should provide a "format" .

**Comment by kapalkat** [comment]
Got it. Thanks! Works fine when I provide  proper format prop.
