### ISSUE TITLE
jqxCalendar - incorrect formatting with the Chinese language

### ISSUE THREAD

**Issue by jqwidgets** [jqwidgets/jQWidgets#328]
The names of the days should be "日 一 二 三 四 五 六" instead of the repeated "星" symbol for the short names.

**Example:**
http://jsfiddle.net/txhi/n7p0hz4j/

**Topic:**
https://www.jqwidgets.com/community/topic/jqxcalendar-globalization

**Comment by windicevista** [comment]
dayNameFormat : "shortest"
