### ISSUE TITLE
jqxGrid - select first cell when clicking on the header

### ISSUE THREAD

**Issue by jqwidgets** [jqwidgets/jQWidgets#336]
**Describe the bug**
Without any selected cell at the beginning.
After pressing **_F12_** button and before that just one click on the header then the first cell from the first column will be selected.

**Steps to reproduce:**
1. In cellsselection.htm, comment out or remove code  $("#grid").jqxGrid('selectcell', 2, "lastname"); 
        });
2. Run cellsselection.htm, when the page loaded click on a blank area of a header.
3. In the keyboard, press F12
4. you will see the first cell in the first column in the first row will be selected, and the cellselect event will be fired up.

**Example:**
https://www.jqwidgets.com/jquery-widgets-demo/demos/jqxgrid/cellsselection.htm?light

**Comment by bmarkov** [comment]
When the Grid gets the focus, the first cell is selected automatically to allow the user to navigate with the keyboard.
