### ISSUE TITLE
ERROR in angular_jqxchart.ts

### ISSUE THREAD

**Issue by Balvindersing** [jqwidgets/jQWidgets#34]
Angular_jqxchart Demo not working.

ERROR in ./node_modules/jqwidgets-scripts/jqwidgets-ts/angular_jqxchart.ts
Module build failed (from ./node_modules/@ngtools/webpack/src/index.js):
Error: E:\gqaixbqm.github\node_modules\jqwidgets-scripts\jqwidgets-ts\angular_jqxchart.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the
'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (E:\gqaixbqm.github\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:767:23)
    at plugin.done.then (E:\gqaixbqm.github\node_modules\@ngtools\webpack\src\loader.js:41:31)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)

**Comment by bmarkov** [comment]
It seems that the TS is not included in the tsconfig file. Please, include a reference to it and it will work.
