### ISSUE TITLE
Theme Builder - incorrect colors of the imported custom theme

### ISSUE THREAD

**Issue by jqwidgets** [jqwidgets/jQWidgets#351]
When trying to import one already created theme from a **JSON** file it does not match all set settings.

**Steps to reproduce the behavior:**
1. Opening the Theme Builder
2. Go to the "ADVANCED SETTINGS" option
3. Switch to the "Tabs" section from the "dropdown" menu
4. Changing colors:
    a. Selected tab background color -> rgba(236, 236, 208, 1)
    b. Selected tab bottom border color -> rgba(211, 211, 187, 1)
    c. Selected tab text color -> rgba(49, 49, 49, 1)
5. Return back to the "Basic Settings" section
6. Export to JSON file format
7. Refresh the Theme Builder to renew it
8. Try to import the created JSON file
9. The selected tab has different colors from the settings before

**Expected behavior:**
To has the same colors as before

**Comment by bmarkov** [comment]
Fixed
