### ISSUE TITLE
jqxNumberInput - changed steps when pressing the arrow-down

### ISSUE THREAD

**Issue by jqwidgets** [jqwidgets/jQWidgets#352]
When pressing the arrow-down it goes from **-0.01** to **-0.11** value.
The expected value should be **-0.02** value.

**Examples:**
https://www.jqwidgets.com/jquery-widgets-demo/demos/jqxnumberinput/number-templates.htm?light
https://www.jqwidgets.com/jquery-widgets-demo/demos/jqxnumberinput/numberinput-fluid-size.htm?light

**Comment by bmarkov** [comment]
Fixed in ver. 11.0.0
