### ISSUE TITLE
jqxGrid - strange behavior when using the "selectionmode" option with the "checkbox" value

### ISSUE THREAD

**Issue by jqwidgets** [jqwidgets/jQWidgets#368]
Incorrect behavior.
When filtering by some value and using the _"**Select All**" option_ it works fine.
After that clearing, the filtered value and there are selected all records from the specific filtering.
This case works OK.

When selecting all rows with the _"**Select All**" option_ _(the checkbox on the upper left corner in the header)_ it is fine at this stage.
After that filtering by one value then using the option to unselect all rows _(uncheck the checkbox in the header)_.
Clearing the filter and the expected scenario is to see unselected only previously filtered records.
This case is not OK.

**Example:**
https://www.jqwidgets.com/jquery-widgets-demo/demos/jqxgrid/checkboxselection.htm?light

**Comment by bmarkov** [comment]
fixed
