### ISSUE TITLE
jqxInput with Material theme in Angular Bug

### ISSUE THREAD

**Issue by MyemaHMN** [jqwidgets/jQWidgets#379]
**Describe the bug**
Using input widget together with Material theme and a source:
If you type in a search text the list opens. Than leave the widget without choosing just by clicking outside the widget, the list is not going to be closed.
This not the expected behaviour. Together with Light Theme the list will be closed. 

**To Reproduce**
1. Go to https://www.jqwidgets.com/angular/angular-input/#https://www.jqwidgets.com/angular/angular-input/angular-input-defaultfunctionality.htm
2. Click on Theme an chose Material.
3. Type in "Sam", list shows "Samoa" (but you want Sam)
4. Klick outside the widget
5. List stays open.

**Expected behavior**
Repeat with Light theme. 

**Desktop (please complete the following information):**
 - OS: [Win]

**Smartphone (please complete the following information):**

**Additional context**

**Comment by bmarkov** [comment]
Fixed for 12.1.0
