### ISSUE TITLE
jqxDataTable - the "enableBrowserSelection" property set to the "true" value does not work properly

### ISSUE THREAD

**Issue by jqwidgets** [jqwidgets/jQWidgets#383]
When the _"**enableBrowserSelection**" property_ is enabled and the _"**selectionMode**" option_ is set to the _"**singleRow**" value_ the row cannot be selected as it is expected.

**Example:**
http://jsfiddle.net/9b8q4a7j/

**Comment by bmarkov** [comment]
Fixed in 12.1.0
