### ISSUE TITLE
jqxGrid - flickering of the "hideshowcolumns.htm" demo

### ISSUE THREAD

**Issue by jqwidgets** [jqwidgets/jQWidgets#393]
Scrolling down and using show/hide options of the column chooser.
The scrollbar should stay in the same position as before.

**Example:**
https://www.jqwidgets.com/jquery-widgets-demo/demos/jqxgrid/hideshowcolumns.htm?light

**Comment by bmarkov** [comment]
Fixed in ver. 12.0.0
