### ISSUE TITLE
jqxGrid - pinned columns go under the "columngroups" options

### ISSUE THREAD

**Issue by jqwidgets** [jqwidgets/jQWidgets#402]
The _"**z-index**" option_ of the pinned columns are smaller related to the _"**columngroups**" option_.
This happens when there are a lot of columns.

**Example:**
https://jsfiddle.net/zs3eygf7/

**Comment by bmarkov** [comment]
columngroups with pinned columns is supported in Smart.Grid but not in jqxGrid.
