### ISSUE TITLE
saveLayout and loadLayout not working correctly

### ISSUE THREAD

**Issue by Crisium** [jqwidgets/jQWidgets#417]
There are two bugs related to this.

1. the saveLayout and loadLayout do not exist in the .d.ts file
2. when you do load the saved layout your floating dialog is created twice.

To reproduce:
1. clone https://github.com/Crisium/jqtest
2. npm install
3. press the button create dialog
4. press the button to save
5. restart browser
6. press the button to load
7. you will now see the floating dialog, move it and you will yet another one underneath it.

**Expected behavior**
For the 1st part of the bug you should be able to call saveLayout and loadLayout from the variable created by the createInstance method.

**Desktop (please complete the following information):**
 - Windows 10
 - Crome
 - Latest Version

**Comment by bmarkov** [comment]
Fixed for 12.2
