### ISSUE TITLE
jqxGrid couple of issues regarding export and dragging column header to group the grid

### ISSUE THREAD

**Issue by yavor-htmlelements** [jqwidgets/jQWidgets#418]
Issue 1
When using 'exportview' format into 'xlsx' method some of the styles from the grid are not applied such as: 
- Column width and text is not displayed properly in it 
- Boolean value is not displayed properly. Its displayed as '0' or '1' or with '#' symbol
- When apply CSS style to alternating rows for example `background-color: green`  the styles are not applied in the exported file.
- Data export doesn't export grouping order.
Code example: 
[dataexportview.zip](https://github.com/jqwidgets/jQWidgets/files/6669989/dataexportview.zip)

Issue 2:
Sometimes 'getselcetedcells' method doesn't return exactly the selected cells
Sample code of the issue from a customer: 
[Sample Test.zip](https://github.com/jqwidgets/jQWidgets/files/6670009/Sample.Test.zip)

Issue 3:
When dragging a column header it has to be  drag it to the line of the filtering box for the grouping to work and it results in bad UI experience
Code  example:
[statusbar.zip](https://github.com/jqwidgets/jQWidgets/files/6670054/statusbar.zip)

**Comment by bmarkov** [comment]
1. In the exported to excel view, the groups are sorted by default by design.
2. Cannot reproduce
3. Fixed
