### ISSUE TITLE
jqxGrid createeditor callback issue 

### ISSUE THREAD

**Issue by yavor-htmlelements** [jqwidgets/jQWidgets#419]
When having a column of the jqxGrid with custom editor  and set the editor to jqxNumberInput with 'min' and 'max' value and edit a cell in that column the 'min' and 'max'  date are not working and user can enter value larger than the max value for example.

Full code example:
[checkboxcolumn.zip](https://github.com/jqwidgets/jQWidgets/files/6671570/checkboxcolumn.zip)
 
Steps for reproducing:
1. Start editing a cell in the 'Quantity' column and enter number over 10
2. When you click on another cell or un focus from the current one the value is not validated and user can enter value larger than the maximum that is set in the jqxNumberInput.

Note: this behavior is not present in a standalone jqxNumberInput

**Comment by bmarkov** [comment]
Fixed in 12.2
