### ISSUE TITLE
"enableSanitize: true" breaks cellsformat in jqxgrid for dates

### ISSUE THREAD

**Issue by jburton0213** [jqwidgets/jQWidgets#420]
Description:
When not setting "enableSanitize: false" on a $(). jqxGrid({}) object, it causes the grid to ignore the cellsformat property on the column object array when formatting dates.

**To Reproduce**
Create grid using example on website.  Include a date property (eg: in '2020-05-11T09:52:00-04:00').  Attempt to set the cellsformat in the columns array such as one mentioned here https://www.jqwidgets.com/jquery-widgets-documentation/documentation/jqxgrid/jquery-grid-cellsformatting.htm?search=jqxgrid .  We use cellsformat: 'MM/dd/yyyy HH:mm', which was working before the upgrade.  Allow grid to load and observe the ignored format.  

**Expected behavior**
Obey cellsformat date format, such as behavior pre 12.1.0

**Desktop (please complete the following information):**
Windows
Chrome, Firefox
most recent jqx release (12.1.0), Chrome 91.0.4472.106.

**Comment by jqwidgets** [comment]
fixed
