### ISSUE TITLE
jqxGrid scrolls to top of the grid when deleting row

### ISSUE THREAD

**Issue by yavor-htmlelements** [jqwidgets/jQWidgets#425]
When having a jqxGrid and like in the following example have a button that deletes a selected row the grid scrolls to its top.

1. Scroll the grid(to the middle or the bottom of it)
2. Select a row no matter which one
3. Click the delete row button and the grid will scroll

Code example which reproduces the issue:
[deleterRowBug.zip](https://github.com/jqwidgets/jQWidgets/files/6830493/deleterRowBug.zip)

**Comment by bmarkov** [comment]
Fixed in 12.2
