### ISSUE TITLE
jqxGrid with paging and theme- arrows for next/previous page are displaced

### ISSUE THREAD

**Issue by yavor-htmlelements** [jqwidgets/jQWidgets#426]
jqxGrid with theme 'ui-start' has the buttons for previous/next page displaced.

![Screenshot_18](https://user-images.githubusercontent.com/75366828/125966488-3e28b5a9-c546-4a8c-8fb3-e00ec97fb13d.png)

Demo of the grid with that theme:
[UiStartThemeGridBug.zip](https://github.com/jqwidgets/jQWidgets/files/6831456/UiStartThemeGridBug.zip)

**Comment by bmarkov** [comment]
Fixed in 12.2
