### ISSUE TITLE
jqxGrid doesn't export properly the 'date' column in excel

### ISSUE THREAD

**Issue by yavor-htmlelements** [jqwidgets/jQWidgets#427]
Exporting Grid with column with dates in it in the excel file the dates are with one day behind the ones which are displayed by the grid.
Grid data:
![Screenshot_30](https://user-images.githubusercontent.com/75366828/126795358-3540b93a-d871-4693-8faa-5eab2b7e47cc.png)

Excel data:
![Screenshot_31](https://user-images.githubusercontent.com/75366828/126795385-634263d5-ab47-4b37-96f7-b7167dd2fda5.png)

Demo for reproducing this case:
[dataexport.zip](https://github.com/jqwidgets/jQWidgets/files/6869372/dataexport.zip)

**Comment by bmarkov** [comment]
That depends on the time-zone information of the dates loaded in the Grid component. The Grid displays dates in local time unless a time-zone info is present in the data source bindings.
