### ISSUE TITLE
jqxDropDownButton isn't focusable on Tab key press

### ISSUE THREAD

**Issue by yavor-htmlelements** [jqwidgets/jQWidgets#428]
jqxDropDownButton doesn't focus itself when changing between elements with tab key/ mouse hover works as intended/ 

Demo for reproducing the issue:
https://www.jqwidgets.com/jquery-widgets-demo/demos/jqxbutton/dropdownbutton.htm?material-purple

In some themes like the 'arctic' the tab key press focuses the component, but not in the light and office or material-purple for example

**Comment by bmarkov** [comment]
Fixed in 12.2
