### ISSUE TITLE
jqxGrid with virtual mode doesn't filter date columns

### ISSUE THREAD

**Issue by yavor-htmlelements** [jqwidgets/jQWidgets#430]
jqxGrid set up with virtualmode to true and having columns with dates doesn't filter the date columns.

When the virtualmode is disabled this behavior is not present.

Code example for reproducing the issue:
[filterIssue.zip](https://github.com/jqwidgets/jQWidgets/files/6907753/filterIssue.zip)

**Comment by bmarkov** [comment]
When virtual mode is enabled, filtering, sorting, etc. is expected to be handled by the developer as the Grid acts only as a view and renders the result of 
```
  rendergridrows: function (params) {
  }
``
