### ISSUE TITLE
jqxGrid bug when having pinned columns doesn't scroll on the next column on key press 

### ISSUE THREAD

**Issue by yavor-htmlelements** [jqwidgets/jQWidgets#437]
When having a jqxGrid column with enough pinned column to take significant amount of the jqxGrid and scroll the grid to the last column on the right with key press or tab key and select the  cells in direction to the pinned columns it doesn't scroll the grid but instead focuses the pinned columns.

Code example:
http://jsfiddle.net/69rb3mnL/

**Comment by bmarkov** [comment]
fixed
