### ISSUE TITLE
jqxGrid addrow method when using with rowPosition parameter doesn't place the row in the right place

### ISSUE THREAD

**Issue by yavor-htmlelements** [jqwidgets/jQWidgets#442]
When having a jqxGrid and sort it and use the 'addrow' method with rowPostion parameter set to 'last' it doesn't add the row at the bottom of the jqxGrid.

Demo for reproducing the issue:
http://jsfiddle.net/jqwidgets/3a4FY/

**Comment by pgoyal123** [comment]
Hello @yavor-htmlelements ,
I have raised a similar issue and have not received a suitable workaround or solution for the same. Please check the raised issue #441.

**Comment by bmarkov** [comment]
When sorting is applied and you add a row to the bottom, the Grid sorting is applied again with the new rows collection. When you remove the sort, you will notice that your new rows are at the bottom position. To select and ensure visible after adding a row, you should use both visible index and bound index. Example: http://jsfiddle.net/d5e7Lcr2/
