### ISSUE TITLE
jqxDropdownList select event is not firing in Safarai (Ipad & iphone)

### ISSUE THREAD

**Issue by yavor-htmlelements** [jqwidgets/jQWidgets#444]
Having a jqxDropdownList in Safari browser on Ipad or Iphone doesn't fire the 'select' event.(Tested on Ipad)

Code example from a customer for reproducing the issue:
http://jsfiddle.net/1Lzxnj2v

**Comment by bmarkov** [comment]
Fixed in 13.1.0
