### ISSUE TITLE
jqxDateTime selection order inside the input with Tab key issue

### ISSUE THREAD

**Issue by yavor-htmlelements** [jqwidgets/jQWidgets#451]
Demo for reproducing the issue:
http://jsfiddle.net/wapL8j4t/14/

**Comment by bmarkov** [comment]
When the focus enters in the datetimeinput, the first element is always focused. Tab key will move to the next date parts until the last one. The next tab key after that moves the focus our of the datetimeinput and focuses the next html element on the web page.
