### ISSUE TITLE
jqxGrid with many columns overlaps a modal jqxWindow 

### ISSUE THREAD

**Issue by yavor-htmlelements** [jqwidgets/jQWidgets#455]
When having a jqxGrid with large number of columns(for example 25-35) and also having a modal jqxWindow above the  jqxGrid the columns are overlapping the jqxWindow.

Example for reproducing the issue:  http://jsfiddle.net/5kf46Lc8/2/

**Comment by bmarkov** [comment]
The bug is that the zindex property of the window is set to a quite small value.
