### ISSUE TITLE
jqxGrid - cannot filtering with the "showfilterbar" property when the "editable" property is enabled

### ISSUE THREAD

**Issue by djhvscf** [jqwidgets/jQWidgets#458]
**Describe the bug**
When the editable is enabled the showfilterbar is not working. The user can't type anything

**To Reproduce**
1. Go to http://jsfiddle.net/txhi/q3750bw1/
2. Try to type something
3. See error

**Expected behavior**
The user should be able to type and filter the grid.

**Desktop (please complete the following information):**
 - OS: Windows and macOS
 - Browser: Chrome
 - Version: 95.0.4638.69

**Comment by bmarkov** [comment]
Fixed for upcoming ver. 13.1.0
