### ISSUE TITLE
jqxGrid - StatusBar Row placed too low

### ISSUE THREAD

**Issue by IvanPeevski** [jqwidgets/jQWidgets#460]
When autoheight is set to true, the status bar, showing aggregates, is placed 2px too low, which makes a hole between the last row and the status bar.
![Aggregates issue](https://user-images.githubusercontent.com/37153196/141809330-04a5346c-94fd-4d70-89a8-f01ed0b23746.jpg)

Demo for reproducing the issue:
https://jsfiddle.net/8obx7udp/1/

**Comment by bmarkov** [comment]
Fixed for ver. 13.1.0
