### ISSUE TITLE
jqxGrid when having localization set and filtering issue

### ISSUE THREAD

**Issue by yavor-htmlelements** [jqwidgets/jQWidgets#464]
When having the localization set and we filter the column with the ```filtertype: "checkedlist"``` (the column is Forma de Pago) the filters clear all the data in the grid.
When the localization is disabled the issue is not present.

Demo for reproducing the issue:
[bindingtoobservablearray.zip](https://github.com/jqwidgets/jQWidgets/files/7604849/bindingtoobservablearray.zip)

**Comment by bmarkov** [comment]
Fixed in 13.2
