### ISSUE TITLE
jqxGrid in filtering issue when the grid is initially loaded( when using show filter row)

### ISSUE THREAD

**Issue by yavor-htmlelements** [jqwidgets/jQWidgets#465]
When having the grid with the filter row property enabled initially the filtering doesn't work correctly. After clearing the filters the filtering starts to work as intended.
[jqWidgetSupport-main.zip](https://github.com/jqwidgets/jQWidgets/files/7634294/jqWidgetSupport-main.zip)

**Comment by bmarkov** [comment]
unable to reproduce with 13.2
