### ISSUE TITLE
jqxWindow doesn't collapse when using multiple widgets if jQuery version is newer than 3.1.1

### ISSUE THREAD

**Issue by IvanPeevski** [jqwidgets/jQWidgets#468]
**Describe the bug**
jqxWindow with `collapsed: true` doesn't collapse when there is another jqx widget in the page, and if jQuery  version is `>=3.2.0`
The jqxWindow collapses if the jQuery version is `3.1.1 or older`

**To Reproduce**
1. Go to [sandbox demo](https://codesandbox.io/s/flamboyant-cloud-7nhof?file=/olderjquery.html:717-726)
2. The two html files are exactly the same, but with different jQuery versions
3. The html file using the latest jQuery version `newerjquery.html` doesn't collapse the jqxWindow

**Comment by bmarkov** [comment]
Works ok with 13.2 and individual scripts references
