### ISSUE TITLE
Feature Request: Add event.arg.type for 'change' event for jqxSwitchButton

### ISSUE THREAD

**Issue by IvanPeevski** [jqwidgets/jQWidgets#469]
Request to add `event.arg.type` property for the `change` event for `jqxSwitchButton`, similar to the existing one for `jqxCheckBox`

Demo for comparison between  `jqxSwitchButton` and `jqxCheckBox`:
https://jsfiddle.net/mogador/q837gxv6/

**Comment by bmarkov** [comment]
Available in 13.2
