### ISSUE TITLE
jqxGrid - exportView - xlsx does not format dates if there is any null values

### ISSUE THREAD

**Issue by IvanPeevski** [jqwidgets/jQWidgets#470]
**Describe the bug**
When there is an empty or invalid date, the generated Excel file from `exportView` doesn't format the date column and displays all other dates as Excel date serial numbers.

**To Reproduce**
Demo of the issue: https://jseditor.io/?key=jqxgrid-issue
After removing the last row, exportView works correctly

**Comment by bmarkov** [comment]
Fixed in 13.2
