### ISSUE TITLE
jqxgrid.js: field name can't be js keyword: `columns should be initialized with unique data fields`

### ISSUE THREAD

**Issue by yurenchen000** [jqwidgets/jQWidgets#471]
jQWidgets v13.1.0 (2021-Nov)
<br>

## 一. description

```js
var columns = [
    {
        "text": "test1",
        "datafield": "push"
    },
    {
        "text": "test2",
        "datafield": "find"
    },
    {
        "text": "test2",
        "datafield": "constructor"
    },
]
```

the err msg when load page:

> Uncaught Error: jqxGrid: Invalid column 'datafield' setting. jqxGrid's columns should be initialized with unique data fields.

<br>

## 二. dig the code

in src of jqxgrid.js

```js
var n = new Array();
...
    if (n[this.datafield]) {
        throw new Error("jqxGrid: Invalid column 'datafield' setting. jqxGrid's columns should be initialized with unique data fields.");
        l.host.remove();
        return false
    } else {
        n[this.datafield] = true
    }
```

<br>

so field name such as `push`,  `toString`, `constructor`... (all methods of Array) will got this error.

<br>

## 三. a workaround

 `.hasOwnProperty(key)` maybe safer than `.[key]` check

```js
// if (n[this.datafield]) {
if (n.hasOwnProperty(this.datafield)) {
```

<br>

**Comment by yurenchen000** [comment]
row filter also have problem with field name `push`.

another workaround (maybe the right way),
use the `map` feature of datafields (avoid use reserved keyword as field name):

```js
datafields: [
         { name: 'id', type: 'number' },
         { name: '_push', type: 'number', map:'push' },
]
```

<br>

then `push` in data source has safer alias name `_push`.

<br>

```js
var columns = [
  { "text": "ID", "datafield": "id", "width": "30" },
  { "text": "push",        "datafield": "_push",    "width": "40"},
]
```

**Comment by bmarkov** [comment]
The uniqueness of the datafield values when columns are initialized is by design. Javascript keywords shouldn't be used as datafields, too. That can be avoided with using name, map pairs in the datafields array initialization as shown in the docs and which it seems you've found, too.
