### ISSUE TITLE
sortmode: 'many' and grouping, after refresh data,  cellclick event .value and rowindex may got undefeind

### ISSUE THREAD

**Issue by yurenchen000** [jqwidgets/jQWidgets#472]
**Describe the bug**
jquery grid with 
- sortmode: 'many',
- groupable: true,  

after refresh data,  cellclick event may got .rowindex and .value `undefined`.
and  dblkclick edit also lose functionianl.

https://www.jqwidgets.com/jquery-widgets-demo/demos/jqxgrid/refreshdata.htm?arctic
use this demo, just some modify:

```js
        // create data grid.
        $("#grid").jqxGrid(
        {
            width: getWidth('Grid'),
            height: 300,

            sortable: true,
            sortmode: 'many',
            groupable: true,  

            editable: true,   
            editmode: 'dblclick',

            source: dataAdapter,
            columns: columns
        });
```

```js
        $("#grid").on("cellclick", function (event, e) {
            // event arguments.
            var args = event.args;
            var datafield = args.datafield; // column data field.
            var value = args.value; // cell value // after refresh or grouping, .value and .rowindex may null

            console.log('== cell click:', datafield, value, args)
        })

```

**To Reproduce**
1. sort by one column
2. group by one column
3. click cell, check console: .value and .rowindex may got `undefined` //also check if dblclick can edit
4. click `refresh` btn
5. click cell, check console //also check if dblclick can edit

**Expected behavior**
after sort,group, refresh data
- cell click event still got right  .rowindex .value  
- dblclick still can edit cell

**Screenshots**

![grid_sort_group_lose_rowindex](https://user-images.githubusercontent.com/8458213/147940260-a7c96525-de6f-43c9-b58e-84f9d536e201.png)

**Desktop (please complete the following information):**
- ubuntu 20 LTS
- chrome 96
- jQWidgets v13.1.0 (2021-Nov)

**Additional context**

without  ` sortmode: 'many'` (disable multi col sort) seems not occur this

**Comment by bmarkov** [comment]
Clicking on group header returns undefined rowindex which is correct behavior, because the group header row is not part of the data source.

**Comment by yurenchen000** [comment]
didn't click on `group header`,  
may be the screenshot not show the behavior clearly, I'll upload a video to descript it.

**Comment by yurenchen000** [comment]
@bmarkov 
will you check it again?

**Comment by yurenchen000** [comment]
> Clicking on group header returns undefined rowindex which is correct behavior, because the group header row is not part of the data source.

@bmarkov 
I don't think we talk about the samething
