### ISSUE TITLE
jqxGrid filtering clears the bound data when used with filter row and custom list items

### ISSUE THREAD

**Issue by yavor-htmlelements** [jqwidgets/jQWidgets#475]
When using the jqxGrid with the following settings from this demo: https://www.jqwidgets.com/jquery-widgets-demo/demos/jqxgrid/filterrowwithcustomitems.htm?light

Filter the grid with some value and the choose the 'Please select' option and the data of the grid is cleared.

**Comment by bmarkov** [comment]
Fixed in 13.2
