### ISSUE TITLE
jqxKanban on 'itemMoved' event returns 'args.NewColumn' as null

### ISSUE THREAD

**Issue by yavor-htmlelements** [jqwidgets/jQWidgets#477]
When moving an item to another column in certaion cases 'args.NewColumn' is null. In the following demo move an item from 'Ready' column to 'Done' column.

Demo for this scenario: http://jsfiddle.net/txhi/4qy0kd1s/914/

**Comment by bmarkov** [comment]
Fixed in 13.2
