### ISSUE TITLE
jqxTextArea - the "select" event does not fire

### ISSUE THREAD

**Issue by jqwidgets** [jqwidgets/jQWidgets#49]
**Example:**
http://jsfiddle.net/85rca90v/

**Comment by bmarkov** [comment]
var textArea = $('#jqxTextArea').jqxTextArea({
    placeHolder: "Enter a Country",
    height: 50,
    width: 200,
    minLength: 1,
    source: countries,
    theme: 'energyblue'
});

textArea.on('select', function (event) {
		console.log(123);
    if (event.args) {
        $("#log").html("An item has been selected.");
    }
});

This is the correct way to fire it.
