### ISSUE TITLE
jqxGrid - date range is lost after LoadState

### ISSUE THREAD

**Issue by IvanPeevski** [jqwidgets/jQWidgets#491]
**Describe the bug**
For a jqxGrid with a date column with celssformat: "dd/MM/yyyy". If there is a date range set in the filter field and the state is saved and loaded, the date range is displayed as **NaN/NaN/0NaN - NaN/NaN/0NaN**
Link to a demo: https://jseditor.io/?key=grid-state-ver-2
![Screenshot (640)](https://user-images.githubusercontent.com/37153196/158849693-7841224f-0474-4520-9bb0-3b8960353a37.png)

**Comment by bmarkov** [comment]
fixed
