### ISSUE TITLE
jqxDataTable - 2nd level nested table disappears

### ISSUE THREAD

**Issue by MartinYotov** [jqwidgets/jQWidgets#499]
When using jqxDataTable with 2 levels nested tables, the row details for the second nested table disappears.

Example: http://jsfiddle.net/z5mLysh9/

**Comment by bmarkov** [comment]
The bug here is in the fiddle. The level 3 table ID is not unique. We have a table with subtable0 as first table for the first expanded row. We have subtable0 for the second row as well. This is also logged in the console.

If we use unique IDs it works as expected. 
```
       function getRandomInt(max) {
                    return Math.floor(Math.random() * max);
                }
                var random = getRandomInt(1000);
                element.append("<div id='" + element.id + "subtable" + random + "' style='margin: 10px;'></div>");


                var table = $($.find('#' + element.id + "subtable" + random));```
