### ISSUE TITLE
jqxTree doesn't work in vue3

### ISSUE THREAD

**Issue by xiameng552180** [jqwidgets/jQWidgets#501]
**Describe the bug**
I've used the demo in vue3 and it doesn't work.
It seems that passing the "source" using props doesn't work and the "source" is not updated.
.
**To Reproduce**
1. Create a vue3 project 3.2.25 using vite.
<img width="254" alt="image" src="https://user-images.githubusercontent.com/31204418/161679307-3b6f29f8-46e3-46af-bac4-d283d565f555.png">

2. Copy and paste the [JSON Tree] demo in https://www.jqwidgets.com/vue/vue-tree/vue-tree-jsontree.htm 
3. The list is not rendered.

**Expected behavior**
The tree should be rendered like this:
<img width="343" alt="image" src="https://user-images.githubusercontent.com/31204418/161679380-849e79f2-62cd-4c1d-82f2-1383c0b612d8.png">

**Comment by bmarkov** [comment]
Our https://www.htmlelements.com/ has Vue 3 support. Our [jQWidgets ](https://www.jqwidgets.com/) product line supports Vue 2.
