### ISSUE TITLE
jqxGrid - filterType:'input' returns error when filterstringcomparisonoperators is localized

### ISSUE THREAD

**Issue by IvanPeevski** [jqwidgets/jQWidgets#507]
When showfilterrow is set to **true** and **filterstringcomparisonoperators** is localized,  filtering in columns with filterType 'input' returns error as there is no default condition selected. If the condition is set manually, the filtering works
The bug doesn't appear with  showfilterrow is set to **false**

Example(third column): [jsfiddle](https://jsfiddle.net/notedop/7nmLo5ds/46/)

**Comment by bmarkov** [comment]
fixed
