### ISSUE TITLE
jqxGrid - editing with columntype: 'datetimeinput' returns 0 when typing the date with keyboard

### ISSUE THREAD

**Issue by IvanPeevski** [jqwidgets/jQWidgets#514]
**Describe the bug**
When editing column with `columntype: 'datetimeinput'`, if the user types the date's day, month or year number with keyboard, the editor sets the value to 0

**To Reproduce**
1. Go to [jsfiddle](https://jsfiddle.net/6n5ov3x1/)
2. Start editing date column
3. Type numbers into the editor

**Additional context**
The issue doesn't appear in the  standalone jqxDateTimeInput widget

**Comment by bmarkov** [comment]
Missing globalize.js
