### ISSUE TITLE
 jqxDateTimeInput - (month-only input) Padding on buttons not applied initially

### ISSUE THREAD

**Issue by Svetoslavb04** [jqwidgets/jQWidgets#517]
**Describe the bug**
The date time input is set to month-only input (views:["year", "decade"]). When you pick a month for the first time the buttons don`t have padding. After the initial selection, the buttons` style is applied and they have padding.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to https://jsfiddle.net/Svetoslavb/4nmx8a69/1/
2. Click on the input
4. See an error
5.  Click on the input again
6. See the applied padding

**Expected behaviour**
The padding should be applied initially

**Comment by bmarkov** [comment]
fixed for v next
