### ISSUE TITLE
jqxGrid - export to xlsx not working with some themes

### ISSUE THREAD

**Issue by IvanPeevski** [jqwidgets/jQWidgets#523]
The issue can be reproduced with the arctic demo:
https://www.jqwidgets.com/jquery-widgets-demo/demos/jqxgrid/dataexport.htm?arctic

The non-working themes are: Arctic, Web, Fresh, Black and Le Frog

For these themes, xlsx export doesn't work with exportdata or exportview

**Comment by bmarkov** [comment]
fixed
