### ISSUE TITLE
jqxGrid filter working incorrectly when using localization with filterchoosestring

### ISSUE THREAD

**Issue by Svetoslavb04** [jqwidgets/jQWidgets#524]
**Describe the bug**
When a custom word for filterchoosestring is set the filter starts working incorrectly. When you filter the data and then try to remove the filter (set the filter option to the default option) no data is displayed

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to https://jsfiddle.net/wo7sa6zh/
2. Click on the filter (All)
3. Choose an option
4. Click on the filter (All)
5. Choose the default option (All)
6.  See error

**Comment by bmarkov** [comment]
fixed for v next
