### ISSUE TITLE
jqxListBox getting wrong selected item when filter is applied

### ISSUE THREAD

**Issue by Svetoslavb04** [jqwidgets/jQWidgets#525]
**Describe the bug**
When the listbox is filterable and you apply some filter the returned value from the getSelectedItem method is wrong

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to http://jsfiddle.net/wnt9563m/1/
2. Type 'b' in the filter area
3. select some item
4. click the button 'Show the selected item'
5. see the bug in the console

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by bmarkov** [comment]
fixed for v next
