### ISSUE TITLE
jqxNumberInput incorrect cursor placement editing negative number

### ISSUE THREAD

**Issue by Svetoslavb04** [jqwidgets/jQWidgets#526]
**Describe the bug**
When entering a NEGATIVE number in the number input and then remove some digit from it the cursor places itself before the last digit before the decimal point.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to https://www.jqwidgets.com/jquery-widgets-demo/demos/jqxnumberinput/index.htm
2. Enter some negative number
3. Set the cursor somewhere between the digits
4. Hit the backspace
5.  See that the cursor always moves before the last digit before the decimal point

**Comment by bmarkov** [comment]
fixed for v next
