### ISSUE TITLE
jqxNumberInput - When spinButtonsStep>10 and min<0, the spinButtons stop working 

### ISSUE THREAD

**Issue by IvanPeevski** [jqwidgets/jQWidgets#527]
`spinButtonsStep>10` and `min<0` and the value of the input is double-digit negative, the spinButtons stop working

Demo for reproducing the issue: https://jsfiddle.net/2hv3n8sx/2/
1. Click on the negative spin button
2. The value goes to -10 and spinbuttons stop working

**Comment by bmarkov** [comment]
fixed for v next
