### ISSUE TITLE
Packaging correctly for angular

### ISSUE THREAD

**Issue by emiltorp** [jqwidgets/jQWidgets#53]
Hi,

Any plans of fixing this?
```
ERROR in ./node_modules/jqwidgets-scripts/jqwidgets-ts/angular_jqxtreegrid.ts
Module build failed (from ./node_modules/@ngtools/webpack/src/index.js):
Error: C:\TRV\Metis.Frontend\node_modules\jqwidgets-scripts\jqwidgets-ts\angular_jqxtreegrid.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them
to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
```

This message especially:
`TS files in published libraries are often a sign of a badly packaged library`

**Comment by bmarkov** [comment]
Thanks for writing.

I would suggest you to take a look at our Angular documentation about how to use our product. 
It is explained here: https://www.jqwidgets.com/angular-components-documentation/documentation/angular-cli/angular-cli.htm how to Include our Typescript files. It seems that you missed to include the TS file within TSConfig and this Error message says exactly that.

**Comment by emiltorp** [comment]
I know that it will work if I include the files. But that is still a sign of a `badly packaged library` according to the angular documentation. 

I realized though, after reading your documentation that you have a properly packaged ng-package (jqwidgets-ng instead of jqwidgets-ts). That should probably the default you promote people to use instead of modifying ts.config. 

Also, instead of this:
```
By now we have a fully working Angular CLI app. But we need to modify it abit so we can use the jQWidgets Framework. Open the angular.json file and inside the styles property add this line:

"node_modules/jqwidgets-scripts/jqwidgets/styles/jqx.base.css"
```

You should probably say this (since you shouldn't need to edit angular.json for a specific package, and this seems to be the consensus for all other package I use):
```
By now we have a fully working Angular CLI app. But we need to modify it abit so we can use the jQWidgets Framework. Open the styles.scss file and add this line:

@import "node_modules/jqwidgets-scripts/jqwidgets/styles/jqx.base.css"
```

However, jqwidgets-ng seems to have an issue with building with the production flag. See #51

**Comment by jqwidgets** [comment]
Thanks for the comments. We will consider them
