### ISSUE TITLE
jqxMaskedInput not removing changing value on 'Delete' key press

### ISSUE THREAD

**Issue by Svetoslavb04** [jqwidgets/jQWidgets#531]
**Describe the bug**
When trying to edit the input with the 'Delete' key the value is not changing only the cursor position is changing

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to https://www.jqwidgets.com/jquery-widgets-demo/demos/jqxmaskedinput/index.htm#demos/jqxmaskedinput/defaultfunctionality.htm
2. Click on any input
3. Enter some digits
4. Try to edit them with the 'Delete' key
5. See an error

**Expected behaviour**
On the 'Delete' key click the input should be changed. The character from the right should be deleted

**Comment by bmarkov** [comment]
fixed for v15
