### ISSUE TITLE
jqxGrid - Export without provided file name does not work

### ISSUE THREAD

**Issue by Svetoslavb04** [jqwidgets/jQWidgets#532]
**Describe the bug**
In the documentation, it said: If you don't provide a file name, the Grid will export the data to a local variable.
But the export does not work without a provided name.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to http://jsfiddle.net/34xo5phe/
2. Click on the button
4. See an error

**Expected behaviour**
It should export a file with the name of the variable

**Comment by bmarkov** [comment]
actually even in the demo it works.
