### ISSUE TITLE
jgxGrid updaterow with array does not update the grid when filter is applied

### ISSUE THREAD

**Issue by Svetoslavb04** [jqwidgets/jQWidgets#533]
**Describe the bug**
When you use updaterow() with an array and after that apply any filter to any column. The next time you try to update the grid an update won't happen. The updaterow() with an array won't work. If you update only one row it will work.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to http://jsfiddle.net/sLokzjq4/
2. Click on the button to update. (It will update the grid)
3. Filter any column
4. Click on the button to update. (It won't update the grid)
5. See an error

**Expected behaviour**
Every time you click the update button the grid should be updated

**Comment by bmarkov** [comment]
fixed for vnext
