### ISSUE TITLE
jqxGrid Charting bug

### ISSUE THREAD

**Issue by Svetoslavb04** [jqwidgets/jQWidgets#535]
**Describe the bug**
Charting does not work. An error is thrown in the console

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to http://jsfiddle.net/cgberxo8/
2. Click on any charting button
3. See the browser console

**Comment by bmarkov** [comment]
fixed. The issue is that dataFields instead of datafields should be used. Now it will work with both options
