### ISSUE TITLE
jqxScheduler - editDialogOpen 'dialog' variable reference

### ISSUE THREAD

**Issue by Svetoslavb04** [jqwidgets/jQWidgets#536]
**Describe the bug**
The first time the editDialogOpen callback is executed the dialog variable correctly references the _editDialog.
After that, each time the function gets executed the dialog variable has got a value of undefined.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to https://codepen.io/svetoslavb04/pen/GRxbPoR
2. Open the browser's console and clear it
3. Double-click on a date in the scheduler and see the correct reference
4. Double-click again and see that the logged value is undefined.

**Comment by bmarkov** [comment]
fixed
