### ISSUE TITLE
jqxDropDownList ANGULAR missing scrollBarSize property

### ISSUE THREAD

**Issue by Svetoslavb04** [jqwidgets/jQWidgets#538]
**Describe the bug**
In Angular is missing the scrollBarSize property

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to https://www.jqwidgets.com/angular-components-documentation/documentation/jqxdropdownlist/angular-dropdownlist-api.htm?search=drop
2. Find the scrollBarSize property and copy the example code into a Angular project
3. See error

**Comment by bmarkov** [comment]
fixed
