### ISSUE TITLE
jqxScheduler Month Days > 31 Bug

### ISSUE THREAD

**Issue by zakk616** [jqwidgets/jQWidgets#539]
**Describe the bug**
While Selecting Repeat Yearly or Monthly. the days selection is not limited. can select a day > 31. 

**To Reproduce**
1. double click to add appointment
2. select 'Monthly' or 'Yearly' in the repeat
3. scroll up 'Days' 

![image](https://user-images.githubusercontent.com/26119949/189861522-6e65da67-a8ea-463a-a65d-9154c70c870c.png)

![image](https://user-images.githubusercontent.com/26119949/189861646-9dc360c0-fa4e-4e4c-be94-f51f4019ed6c.png)

4. after adding the appointment with this selected days the scheduler only produces an error in console when below code runs.

`var aptmnts = $('#scheduler').jqxScheduler('getAppointments'); `

![image](https://user-images.githubusercontent.com/26119949/189862580-f8564858-9194-487f-87c3-e629c204e883.png)

**Comment by bmarkov** [comment]
will be part of the next release
