### ISSUE TITLE
jqxGrid - cellvaluechanged event is beinged trigger when cell's type is date

### ISSUE THREAD

**Issue by SvetoslavjQWidgets** [jqwidgets/jQWidgets#540]
**Describe the bug**
When a cell is with type 'date' the value is an object.
If you double click to edit a cell and navigate through the grid with 'tab' for example and face a cell with a value of an object,
the old and the new object are being compared and the cellvaluechanged event is being triggered even though the values are equal.
This happens because the objects are being compared by reference and the references are different.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to http://jsfiddle.net/1wo2ve65/
2. Double-click on the leftmost
3. Navigate with 'tab'
4. See that the event is triggered (in console)

**Comment by bmarkov** [comment]
fixed
