### ISSUE TITLE
jqxPasswordInput (Angular)- change event not triggering properly

### ISSUE THREAD

**Issue by SvetoslavjQWidgets** [jqwidgets/jQWidgets#541]
**Describe the bug**
In Angular when you try to set a handler for the change event, the handler is not properly involved.
When you try to set it with (onChange) the handler is being invoked onBlur and when you set it with (change) it is not invoked at all.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to https://stackblitz.com/edit/github-oxa9fd?file=src/app/app.component.html
2. Open the console
3. See an error

**Comment by bmarkov** [comment]
It is incorrect to set it with (change). Correct is only with onChange. Ref: https://www.jqwidgets.com/angular-components-documentation/documentation/jqxpasswordinput/angular-passwordinput-api.htm In the API docs 

```
import { Component } from "@angular/core";
 
@Component({
    selector: "app-root",
    template: `
        <jqxPasswordInput #myPasswordInput (onChange)="Change($event)"
            [width]="300" [height]="21">
        </jqxPasswordInput>
    `
})
 
export class AppComponent {
    Change(event: any): void 
    {
        // Do Something
    }

    
}
```
