### ISSUE TITLE
React jqxPasswordInput val method does not set the correct value

### ISSUE THREAD

**Issue by SvetoslavjQWidgets** [jqwidgets/jQWidgets#555]
When you try to reset the input in the jqxPasswordInput the method does not set the value to an empty string:
this.passwordInputRef.val(''); - this does nothing

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to https://easyupload.io/3y5gkd
2. Download the project
3. Open a terminal in the folder
4. Run npm install
5. Run npm start
6. Type something in the password box
7. Click Reset
8. See an error

**Comment by bmarkov** [comment]
fixed
