### ISSUE TITLE
Grid - The sort order icons appear only for some themes.

### ISSUE THREAD

**Issue by IvanPeevski** [jqwidgets/jQWidgets#564]
The sorting order icon appear only for the light/dark theme.
The other themes are missing a "role" attribute to the `.sorticon`
Light: https://www.jqwidgets.com/jquery-widgets-demo/demos/jqxgrid/grid-multi-column-sorting.htm?light
Material: https://www.jqwidgets.com/jquery-widgets-demo/demos/jqxgrid/grid-multi-column-sorting.htm?material
Energy Blue: https://www.jqwidgets.com/jquery-widgets-demo/demos/jqxgrid/grid-multi-column-sorting.htm?energyblue

**Comment by bmarkov** [comment]
by design only the new themes supports this feature
