### ISSUE TITLE
jqxMaskedInput - Caps Lock key has no effect

### ISSUE THREAD

**Issue by IvanPeevski** [jqwidgets/jQWidgets#580]
**Describe the bug**
When writing in a jqxMaskedInput, the input ignores the caps lock and will interpret the new character as a lower case value.
The same issue doesn't appear if the users writes capitcal letters with Shift+[letter]

**To Reproduce**
1. Example: https://jsfiddle.net/yjax2osL/
2. Activate Caps Lock and type

**Comment by bmarkov** [comment]
FIXED
