### ISSUE TITLE
jqxGrid: column property filterable does not work in filterbarmode: 'simple'

### ISSUE THREAD

**Issue by SvetoslavjQWidgets** [jqwidgets/jQWidgets#594]
Te Grid has a filter bar and the mode is simple. You want to exclude a column from the filter and set the filterable property in the column definition to false. Now the expected result is that when you filter the Grid it will exclude the data from that column.
But the filterable property does not work when the filterbarmode is simple.

**To Reproduce**
1. Go to http://jsfiddle.net/h379qwvs/
2. Type some number from the Quantity or Price column
3. Apply the filter
4. See that the Grid is filtered by the columns on which the filtering is disabled

**Comment by bmarkov** [comment]
fixed
