### ISSUE TITLE
jqxGrid: No default selection in the filter dropdown

### ISSUE THREAD

**Issue by SvetoslavjQWidgets** [jqwidgets/jQWidgets#596]
When the localization settings for 'filterstringcomparisonoperators' are changed, the default value of the operators drop-down list is not set: 

**To Reproduce**
1. Go to http://jsfiddle.net/4h3rujcL/
2. Click to open the filter drop-down of the Produkt column
3. See that there is no default value

**Comment by bmarkov** [comment]
This is by design
