### ISSUE TITLE
jqxWindow - iframe content is emptied on first open if the iframe content was set with a form target

### ISSUE THREAD

**Issue by IvanPeevski** [jqwidgets/jQWidgets#605]
**To Reproduce**
1. Place an iframe inside of jqxWindow. 
2. Create a form with `target` attribute set to the iframe.
3.  Submit the form
4. When the form is submitted, the server response is set to the iframe
5. When the jqxWindow is opened, the iframe is emptied (BUG)
6. Close window and resubmit form
7. Reopen the window and this time the iframe won't be emptied.

Exmaple: https://jsfiddle.net/due5kr2j/

Note: When initContent is called, the iframe content is already cleared

**Comment by bmarkov** [comment]
This is only possible when you add the IFRAME within the initContent dynamically to the window. Otherwise, when iframe is wrapped in jqxWindow it is reloaded.
