### ISSUE TITLE
jqxGrid - comboBox dropdown visual issue for Android

### ISSUE THREAD

**Issue by IvanPeevski** [jqwidgets/jQWidgets#622]
From a client:

JqxGrid – Combobox dropdown showing different behaviour On Android and iPhone/Desktop

On desktop and iPhone – dropdown is showing properly on top of that row in grid, but in android view – dropdown is going somewhere to bottom of the screen as attached screenshots below

 

Please check why this combobox is showing different behaviour on different screens..

 

On iPhone: 
![image001](https://user-images.githubusercontent.com/37153196/235212190-7de7b3b5-aec7-4435-a79e-2c143b81e48a.png)

On desktop :
![image003](https://user-images.githubusercontent.com/37153196/235212241-03671001-2490-4769-b99c-9d693fcc9cb4.png)

On Android:
![image002](https://user-images.githubusercontent.com/37153196/235212221-4b163a90-eedd-4761-882a-7f1ef8454bfc.png)

 

Code:
`
text: 'Problem Aggregate', displayfield: 'paName', columntype: 'combobox', datafield: 'problemAggregateId', width: 200, createeditor: this.createGridEditor1,editable: true,
`

`createGridEditor1 = (row: number, value: any, editor: any): void => {
      editor.jqxComboBox({
      source: this.allProblemAggregatesList,
      displayMember: 'name',
      valueMember: 'id'
    })
  }
`

`<jqxGrid #myGrid [theme]="'custom-scheme'" [width]="getWidth()" [height]="100" [source]="source"
                    [showstatusbar]="true" [editable]="isProblemGridEditable" [showaggregates]="true"
                    [statusbarheight]="25" [autoheight]="true"
                    (onCellendedit)="myGridOnCellEndEdit($event)" [columns]="columns" [selectionmode]="'singlerow'"
                    [editmode]="'click'" [columnsresize]="true">
                </jqxGrid>`

**Comment by bmarkov** [comment]
fixed
