### ISSUE TITLE
jqx.base.css - CSS rule for input[type="number"] is too general and affects non-jqx elements

### ISSUE THREAD

**Issue by IvanPeevski** [jqwidgets/jQWidgets#630]
jqx.base.css contains these CSS rules:
`input::-webkit-outer-spin-button,
input::-webkit-inner-spin-button {
    -webkit-appearance: none;
    margin: 0;
}`
`/* Firefox */
input[type=number] {
    -moz-appearance: textfield;
}`
It hides the up/down arrows for all number inputs in the page even if they are not jqx widgets

**Comment by bmarkov** [comment]
fixed
