### ISSUE TITLE
jqxGrid: Incorrect selection when server side grid is applied

### ISSUE THREAD

**Issue by SvetoslavjQWidgets** [jqwidgets/jQWidgets#633]
**Describe the bug**
When there is a server-side pagination and the selection is enabled a strange behaviour occurs.
When you select rows, and then filter, the rows which are selected are not by id but by index. This means that if before filtering I have selected rows with ids 2, 5 and their row positions in the grid are 2 and 5, after filtering the selected rows would be this that are on positions 2 and 5, not the rows with id 2, 5

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to https://jsfiddle.net/ph56bwmL/
2. Click on some rows to select them
3. Type something in the first Name filter input
4. See an error

**Comment by bmarkov** [comment]
in virtual mode the selection is by index by design
