### ISSUE TITLE
jqxGrid: Saving state saves column widths in pixels, not in percentages

### ISSUE THREAD

**Issue by SvetoslavjQWidgets** [jqwidgets/jQWidgets#637]
**Describe the bug**
Column widths are set in percentages in the column definition object. But when there is a autosavestate, it saves the state to the local storage and there the column widths are not represented in percentages but in pixels

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to https://jsfiddle.net/jqwidgets/X68HN/284/
2. Click on a column to sort (triggers state save)
3. In Dev tools find the object in the local storage and see that the values are stored in pixels
4. Reload the app
5. Change the size of the view
6. See that the columns do not fill the grid because of the saved state

**Comment by bmarkov** [comment]
fixed
