### ISSUE TITLE
jqxGrid: when sortmode many is active, savestate saves only the last sorting

### ISSUE THREAD

**Issue by Svetoslavb04** [jqwidgets/jQWidgets#640]
**Describe the bug**
When sort mode many is active, savestate saves only the last sorting

**To Reproduce**
1. Go to https://jsfiddle.net/mogador/th5j3dLv/
2. Sort grid with columns [In Stock] and [Quantity]
3. Click on savestate
4. Clear the sortings on columns [In Stock] and [Quantity]
5. Sort grid on column [product]
6. click on [Load State]
7. See that only quantity is loaded as sorting and the product sorting stays

**Comment by bmarkov** [comment]
fixed
