### ISSUE TITLE
jqxTreeGrid: Editing a single row changes two rows

### ISSUE THREAD

**Issue by Svetoslavb04** [jqwidgets/jQWidgets#643]
**Describe the bug**
There is a grid, it has hierarchy with keyDataField: 'partid', parentDataField: 'parentid' and unique id: 'id'.
In the example, there are two rows with the same 'name' but different ids; when you edit one of the rows, the other is also updated.

**To Reproduce**
1. Go to https://jsfiddle.net/gz9wejd2/1/
2. Expand the two rows
3. Edit the quantity column of one of the 'Child Black Tea'

**Comment by bmarkov** [comment]
incorrect sample. partid here is the id.
