### ISSUE TITLE
Vue3 jqxDataTable: columnGroups hierarchy does not work

### ISSUE THREAD

**Issue by SvetoslavjQWidgets** [jqwidgets/jQWidgets#645]
**Describe the bug**
A user copied and pasted a demo from the website in Vue3 but an error is received:
jqxDataTable: Column Groups initialization Error. Please, check the initialization of the jqxDataTable's columns array. The columns in a column group are expected to be siblings in the columns array.

The same demo runs in vanilla js

The demo from the site:
https://www.jqwidgets.com/vue/vue-datatable/#https://www.jqwidgets.com/vue/vue-datatable/vue-datatable-columnshierarchy.htm

**To Reproduce**
1. Go to https://codesandbox.io/s/blissful-curie-tl4wm6?file=/src/components/HelloWorld.vue
2. See error

**Comment by bmarkov** [comment]
fixed
