### ISSUE TITLE
jqxGrid - 'getgroup' doesn't return the "expanded" state

### ISSUE THREAD

**Issue by IvanPeevski** [jqwidgets/jQWidgets#648]
Example: https://jsfiddle.net/jqwidgets/tbCwt/

According to the API, 'getgroup' should return the following fields:

- group - group's name.
- level - group's level in the group's hierarchy.
- expanded - group's expand state.
- subrows - an array of rows or null.

But the expanded property is missing

**Comment by bmarkov** [comment]
fixed
