### ISSUE TITLE
jqxGrid: cutom filter widget as drop down

### ISSUE THREAD

**Issue by SvetoslavjQWidgets** [jqwidgets/jQWidgets#649]
**Describe the bug**
There is a situation where the grid's filter row is a custom widget and is a drop-down with checkboxes.
When you search for an item in the drop-down and try to select the first one, it cannot be selected

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to https://jsfiddle.net/v31kphub/1/
2. Click on 'Select filter' of the first column
3. Type 'c' in the search field
4. See that the first checkbox cannot be deselected
5. Remove 'c'
6. Deselect everything
7. Type 'c' again
8. See that the checkbox cannot be selected

**Comment by bmarkov** [comment]
This custom widget will require customization of the default selection logic for the select all item or removing the select all item when filtering is enabled in the dropdown.
