### ISSUE TITLE
jqxGrid: columnresize property cannot be changed dynamic

### ISSUE THREAD

**Issue by SvetoslavjQWidgets** [jqwidgets/jQWidgets#651]
**Describe the bug**
If you try changing the columnresize property dynamically, the value will be changed but the behaviour will be as initially set.

**To Reproduce**
1. Go to https://jsfiddle.net/8f47vq3y/
2. Resize any column
3. Click the button to disable resizing
4. See that you are able to resize any column, but you should not

**Comment by bmarkov** [comment]
fixed
