### ISSUE TITLE
jqxGrid: Validation tooltips not in correct order and position

### ISSUE THREAD

**Issue by SvetoslavjQWidgets** [jqwidgets/jQWidgets#652]
**Describe the bug**
When validations are enabled, the order of the messages is not correct

**To Reproduce**
1. Go to https://jsfiddle.net/jpeszleny/fowqrm1L/4/
2. Double-click on the first cell of the first row (edit the empty row)
3. Now click somewhere to trigger the validation
4. See that the validation message appears for the drop-down
5. Now, select a value from the drop-down
6. Trigger validation
7. See that now the message appears for the last name, but in the first name's colum

**Comment by bmarkov** [comment]
fixed
