### ISSUE TITLE
jqxDocking with Angular *ngFor

### ISSUE THREAD

**Issue by VijayanRamachandran** [jqwidgets/jQWidgets#653]
Hi,

I am facing an issue in below scenario.

If i try to use jqxDocking together with angular constructs such *ngFor then the result is not as expected..

Example:

In the below code snippet, i have used *ngFor in first div tag within jqxDocking with expectation that all the entries in the pool binded variable with docked vertically as rendered within div tag. But application does not rendering it as docked vertically.

                   <jqxDocking 
                           [orientation]='"vertical"' 
                           [width]='400' 
                           [mode]='"floating"' 
                           [theme]="'dark'" >
                     <div *ngFor="let image of pool" >
                        <div>
                           <div>
                              {{ image.Name }} / {{ image.Count }}
                           </div>
                           <div>
                              <custom-image-display style='height: 200px; width: 200px;' 
                                                [id]="image.Name">
                              </custom-image-display>
                           </div>
                        </div>
                     </div>                     
               </jqxDocking>

But without using *ngFor within jqxDocking , if i try to statically render data one by one with hardcoded values, then application is working as expected.

<jqxDocking 
  [orientation]='"horizontal"' 
  [width]='800' 
  [mode]='"docked"' 
  [theme]="'dark'"
  >
  <div>
    <div id="window1" style="height: 220px;">
      <div>
        Date and Time
      </div>
      <div style="overflow: hidden;">
        <jqxCalendar 
          [width]='180' 
          [height]='180' 
          style="float: left; margin-right: 10px;">
        </jqxCalendar>
        <h3 style="text-align: center; color: #787878;">Sunny</h3>
        <div style="float: left; margin-left: 30px; text-align: center;">

        </div>
        <div
          style="text-align: left; margin-left: 5px; margin-top: 10px; 
          font-size: 10px; float: right; margin-right: 20px;">
          Mo: 23 C<br />
          To 25 C<br />
          We: 27 C
        </div>
      </div>
    </div>

    <div id="window2" style="height: 220px">
      <div>
        News
      </div>
      <div style="overflow: hidden;">
        <jqxTabs 
          [width]='375' 
          [height]='181' 
          [selectedItem]='1'>
          <ul style="margin-left: 30px">
            <li>World</li>
            <li>Local</li>
            <li>Sports</li>
          </ul>
          <div>
            <div style="padding: 3px; margin: 10px; width: 150px; height: 84px; float: left;">
              <img src="assets/images/news_ie6.jpg" alt="IE6" title="IE6" />
            </div>
            <span style="font-size: 11px;">
              Microsoft is set to get a little more pushy ensuring
              you have an up-to-date browser and will automatically update Internet Explorer...
              <span style="font-size: 8px;">(BBC)</span>
            </span>
          </div>
          <div>
            <div style="padding: 3px; margin: 10px; width: 144px; height: 81px; float: left;">
              <img src="assets/images/local.jpg" alt="Tennis" title="Tennis" />
            </div>
            <span style="font-size: 11px;">
              The High Court has dismissed a challenge to laws that
              require immigrant spouses to be able to speak English in order to live in the UK...
              <span style="font-size: 8px;">(BBC)</span>
            </span>
          </div>
          <div>
            <div style="padding: 3px; margin: 10px; width: 130px; height: 73px; float: left;">
              <img src="assets/images/tennis.jpg" alt="Tennis" title="Tennis" />
            </div>
            <span style="font-size: 11px;">
              British number one Elena Baltacha says Judy Murray is
              a "fantastic" appointment as Great Britain's new Fed Cup captain... <span
                style="font-size: 8px;">(BBC)</span>
            </span>
          </div>
        </jqxTabs>
      </div>
    </div>
  </div>
</jqxDocking>

Can you please hint us what is wrong or this is known problem already that jqx and *ngFor constructs will not work together ?

Regards,
Vijayan Ramachandran

**Comment by bmarkov** [comment]
For using ngFor, you can try the jqxSplitLayout component instead.
