### ISSUE TITLE
Angular: SplitLayout not initializing

### ISSUE THREAD

**Issue by SvetoslavjQWidgets** [jqwidgets/jQWidgets#669]
A client reported receiving an error in the console when using the split layout.
Here is the default demo of the split layout in angular.
When you launch the app the following error is received:

jqxsplitlayout.js:8 Uncaught ReferenceError: b is not defined

**To Reproduce**
Steps to reproduce the behaviour:
1. Open this demo: 
[demo.zip](https://github.com/jqwidgets/jQWidgets/files/13213054/demo.zip)

2. Install the dependencies
3. Run the app

**Comment by bmarkov** [comment]
fixed
