### ISSUE TITLE
jqxEditor

### ISSUE THREAD

**Issue by SvetoslavjQWidgets** [jqwidgets/jQWidgets#682]
The dropdowns for the font colour and background colour are with smaller z-index than the modal,
This causes them to be hidden when the editor is used in modals

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to https://jsfiddle.net/ep0gr7wx/4/
2. Click on the open button
3. Click the corresponding dropdown buttons

**Comment by bmarkov** [comment]
fixed
