### ISSUE TITLE
jqxKanban: cannot updateItem without tags

### ISSUE THREAD

**Issue by SvetoslavjQWidgets** [jqwidgets/jQWidgets#683]
**Describe the bug**
The user wants to update a kanban item, but in the kanban, the 'tags' are not used, so in the updateItem he is passing tags: null.
This throws an error because of the following line in updateItem function:

var o = h.tags.replace(/\,\s/g, ",").split(","); 
(Note that this is minified and the name of the variables are different in the source)

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to https://jsfiddle.net/n96arwqe/
2. Click on the button
3. See error

**Comment by bmarkov** [comment]
fixed
