### ISSUE TITLE
jqxNumberInput - can't enter decimal point on mobile devices

### ISSUE THREAD

**Issue by IvanPeevski** [jqwidgets/jQWidgets#684]
Example (open on mobile) - https://www.jqwidgets.com/jquery-widgets-demo/demos/jqxnumberinput/defaultfunctionality.htm?material

The keyboard which opens on mobile is only for entering numbers and the decimal point can't be inserted, only deleted
Tested on IOS

**Comment by bmarkov** [comment]
fixed
