### ISSUE TITLE
jqxGrid - applying state to grouped grid sometimes reorders the columns incorrectly

### ISSUE THREAD

**Issue by IvanPeevski** [jqwidgets/jQWidgets#685]
For a grid with column reorder and state maintenance, reordering a grouped column and refreshing the page places the column in the wrong order.

Example - https://jsfiddle.net/tLvpb6qg/

1. Group by Product
2. Reorder by dragging Product after Quantity
3. Refresh page
4. Product appears after First Name

There is a workaround in the ready function by moving the columns to their index + 1. So I think it may be related with the expand/collapse column shifting the indexes somehow

**Comment by bmarkov** [comment]
fixed
