### ISSUE TITLE
jqxGrid - 'getselectedcells' sometimes returns wrong result

### ISSUE THREAD

**Issue by IvanPeevski** [jqwidgets/jQWidgets#690]
Example - https://jsfiddle.net/jqwidgets/kBNWp

To reproduce:
1. Select cell on row index 1, column:firstname
2. Select cell on row index 0, column:lastname
3. Click on "Get selected"
4. The result shows:
Row: 0, firstname
Row: 1, lastname
Row: 0, firstname
Row: 0, lastname

**Comment by bmarkov** [comment]
fixed
