### ISSUE TITLE
jqxDropDownList - 'change' event bug

### ISSUE THREAD

**Issue by IvanPeevski** [jqwidgets/jQWidgets#691]
The 'change' event doesn't when using keyboard to select an item

To reproduce:

- https://jsfiddle.net/x6L5t4kc/1/
- Open the dropdown list with the mouse
- Press the ‘c’ key to highlight Café Bombon
- Use the mouse to click on the highlighted item
- Notice that the ‘changed’ event does not fire and the alert is not displayed.

**Comment by bmarkov** [comment]
fixed. change event is raised while you type, too. Fix is scheduled for next version.
