### ISSUE TITLE
Grid - column reorder duplicates column over another.

### ISSUE THREAD

**Issue by IvanPeevski** [jqwidgets/jQWidgets#693]
Sometimes dragging columns in specific order can duplicate one column over another.

Example - https://jsfiddle.net/jkL592mc/
Steps to reproduce:
1. Drag "Available" between "Quantity" and "Unit price"
2. Drag "Unit price" between "Product" and "Quantity"
3. Drag "Unit price" to the last position
4. Now "Available" has the same content as "Quantity"
5. The issue seems to happen only if the column is "checkbox" type

**Comment by bmarkov** [comment]
fixed for vnext
