### ISSUE TITLE
jqxCheckBoxGroup - issues

### ISSUE THREAD

**Issue by IvanPeevski** [jqwidgets/jQWidgets#694]
There are several issues with the jqxCheckBoxGroup

Demo - https://jsfiddle.net/gr3p7dth/
-  An error occurs when the ‘disabled’ attribute is set to true. Doesn't happen if the "disable" method is used
- If the ‘change’ attribute is not specified, values cannot be retrieved using the ‘val’ or ‘getValue’ method.
- Setting values in disabled state doesn't trigger the 'change' attribute. This can be verified by clicking "Disable" and "Set Items"

**Comment by bmarkov** [comment]
fixed for vnext
