### ISSUE TITLE
jqxPopover - not closing if another button is clicked

### ISSUE THREAD

**Issue by IvanPeevski** [jqwidgets/jQWidgets#695]
jqxPopover with autoClose:true is not closing if a button was clicked
Example - https://jsfiddle.net/za9qoft2/2/

Steps to reproduce:
1. Click on Popover Button 1
2. Click anywhere on the window and the popover will close
3. Open the Popover 1 again and click on Popover Button 2
4. Both Popovers stay open.
5. Closing the window will also leave them open

**Comment by bmarkov** [comment]
fixed for vnext
