### ISSUE TITLE
DockingLayout - issue with "IDE-like Layout" demo

### ISSUE THREAD

**Issue by IvanPeevski** [jqwidgets/jQWidgets#709]
The **IDE-like Layout** is currently broken. In the javascript function, there is a unescaped text: "</script>" which breaks the browser parsing
Link to demo - https://www.jqwidgets.com/jquery-widgets-demo/demos/jqxdockinglayout/index.htm#demos/jqxdockinglayout/javascript-docking-layout-ide-like.htm

**Comment by bmarkov** [comment]
fixed
