### ISSUE TITLE
multiple upload doesn't work in jqxUploader 

### ISSUE THREAD

**Issue by PYovchevski** [jqwidgets/jQWidgets#713]
**Describe the bug**
There is a problem with the multiple upload in jqxUploader

**To Reproduce**
1. Go to ['demo'](https://jsfiddle.net/jqwidgets/e3zshL7L/)
2. Try to upload multiple files

**Comment by bmarkov** [comment]
multipleFilesUpload: false is set in the demo. This is the reason why it does not allow you to upload multiple filex
