### ISSUE TITLE
jqxScheduler - rowsHeight not applying if set during initialization

### ISSUE THREAD

**Issue by IvanPeevski** [jqwidgets/jQWidgets#715]
The "rowsHeight" property is not getting applied if it is set during the scheduler initialization, but it works fine if it is set after the initialization

Example - https://jseditor.io/?key=jqxscheduler-rowsheight-property-ver-2
1. Run demo - the height is still the default one
2. Uncomment the line $("#scheduler").jqxScheduler({rowsHeight: 8}) - it will work correctly

**Comment by bmarkov** [comment]
fixed
