### ISSUE TITLE
Can't bind to 'ngModel' since it isn't a known property of 'input' Angular 7

### ISSUE THREAD

**Issue by antb-developer** [jqwidgets/jQWidgets#75]
I am using jqxSchedulerComponent in angular 7 & jqwidgets-framework 7.1.0. Getting this error when doing ng serve

**Comment by antb-developer** [comment]
Exact console error

Can't bind to 'ngModel' since it isn't a known property of 'input'. ("<input [ERROR ->][(ngModel)]="ngValue">"): ng:///AppModule/jqxDateTimeInputComponent.html@0:7

**Comment by bmarkov** [comment]
Can you provide stackblitz sample?

**Comment by joandylevi** [comment]
import { FormsModule } from '@angular/forms';

[...]

@NgModule({
imports: [
[...]
FormsModule
],
[...]
})

Full code Available [Here](https://icetutor.com/question/cant-bind-to-ngmodel-since-it-isnt-a-known-property-of-input/)
