### ISSUE TITLE
jqxGrid Create React App

### ISSUE THREAD

**Issue by mswpac** [jqwidgets/jQWidgets#78]
Hi,

I have followed the steps outlined here: https://www.jqwidgets.com/reactjs-components-documentation/documentation/create-react-app/index.htm

jqwidgets and jqwidgets-react have been copied to the src/assets/ directory.

My component looks like this:

```
import JqxGrid, { jqx } from "assets/jqwidgets-react/react_jqxgrid";
import React, { Component } from "react";

export default class extends Component {
  render() {
    const { datagrid } = this.props;
    const { columns, source } = datagrid;
    let data = new jqx.dataAdapter(source);

    return (
      <JqxGrid
        autoheight={true}
        columns={columns}
        pageable={true}
        sortable={true}
        source={data}
        width="100%"
      />
    );
  }
}
```

However, on page load I get this error (compilation is slow but does not report any errors):

```
TypeError: Cannot set property 'originalVal' of undefined
eval
C:\Users\X\Projects\moms\ui\src\assets\jqwidgets\jqxcore.js:15:98921
```

I have seen this issue, I can't downgrade my React version as I am using new features: https://www.jqwidgets.com/community/topic/basic-tutorial-doesnt-work/

Are there any solutions I can try?

**Comment by jqwidgets** [comment]
Hello,

Thank you for this feedback.
I would like to recommend you to use the _"**jqwidgets-react-tsx**"_.
The documentation for it will be available on our site soon.

Best Regards,
Hristo Hristov

jQWidgets team
https://www.jqwidgets.com
