### ISSUE TITLE
jqxGrid - when using Adaptive Layout the dropdowns content of the filter menu appear beneath it

### ISSUE THREAD

**Issue by jqwidgets** [jqwidgets/jQWidgets#83]
When 'adaptive' and 'filtering' properties are set to true, after opening a filter menu of the overlay columns,
the content of the dropdowns of all filter menus starts to appear beneath the menu.
Fixed by setting a larger z-index.

Example: http://jsfiddle.net/h5mr38we/

**Comment by bmarkov** [comment]
Closed due to inactivity
