### ISSUE TITLE
jqxPivotGrid - jqxPivotDesigner does not show dialog when it has a lot of items

### ISSUE THREAD

**Issue by jqwidgets** [jqwidgets/jQWidgets#87]
In the case when collecting more items in the _listbox_ the options with dialog does not appear anymore.
When clicking on the "item-button".

_How to reproduce it:_
- add more items into the "Values" _listbox_
- scrolling down and try to click on the "item-button"

<br/>

**Example:**
https://www.jqwidgets.com/jquery-widgets-demo/demos/jqxpivotgrid/pivotgrid_designer.htm?light

**Video example:**
https://cl.ly/b827ce8d3b3a

**Comment by bmarkov** [comment]
Closed due to inactivity
