### ISSUE TITLE
Why react Jqx widget does not re-render on state change?

### ISSUE THREAD

**Issue by dhope-nagesh** [jqwidgets/jQWidgets#93]

**Comment by bmarkov** [comment]
It re-renders when you use jqwidgets-react-tsx. This is our current implementation. The old one will be deprecated in a few weeks.

**Comment by dhope-nagesh** [comment]
@bmarkov is there any roadmap to migrate jsx based code to tsx? Also is jqwidgets-react-tsx is still in beta?

**Comment by bmarkov** [comment]
jqwidgets-react-tsx is still in beta and is part of the download package.  In a few weeks, it goes live on our website.

**Comment by dhope-nagesh** [comment]
@bmarkov is React Jqx Widget also in beta?

**Comment by bmarkov** [comment]
No it is not. It is in production for several years.
